/* English daily content. 90 of each, so the rotation takes three months to come
   back around instead of two weeks — the solo list used to be 15 long, which is
   how a free user met the same question twice before they'd formed any habit. */

export const pair = [
  "Something small that made me smile today…",
  "Something I'd love for us to do together this month…",
  "If today were a picture, it would be…",
  "Something you did recently that I'm grateful for…",
  "A song that reminded me of you today…",
  "Something I want to tell you but haven't yet…",
  "My favorite moment of today, in one sentence…",
  "Something small you do that I don't say enough how much I love…",
  "A place I'd love to go with you someday…",
  "Something I learned about myself today…",
  "If I could relive one hour from today, it would be…",
  "A tiny thing I'm looking forward to this week…",
  "Something that made me think of \"us\"…",
  "A word that describes today…",
  "Something I wish I'd said out loud today…",
  "A memory of ours that made me smile just now…",
  "Something I'm proud of you for…",
  "A little thing you could do that would make my day…",
  "Something I noticed about you today…",
  "If today had a soundtrack, it would be…",
  "A question I've been wanting to ask you…",
  "Something that felt like \"home\" today…",
  "A tiny adventure I'd like us to have…",
  "Something I'm grateful for about us…",
  "A moment today I want to remember…",
  "Something I'm curious about you…",
  "A small kindness I noticed today…",
  "Something that made today feel lighter…",
  "A dream I had (for us) about the future…",
  "Something I'd like more of, in us…",
  "The last time you made me laugh out loud…",
  "Something I'd want you to know if today were the only day…",
  "A habit of yours I've quietly come to love…",
  "Something I found hard today, and didn't say…",
  "The smallest thing that went right today…",
  "A meal I'd like to make (or eat) with you…",
  "Something about today I'd happily do again tomorrow…",
  "A way you made today easier without meaning to…",
  "Something I'm still thinking about from earlier…",
  "What I'd like our next free Saturday to look like…",
  "A photo of us I thought about today…",
  "Something I want us to stop rushing…",
  "The moment today I felt most like myself…",
  "Something I'd like to thank you for, specifically…",
  "A small worry I'd rather hand over than hold…",
  "Something you said once that I still carry…",
  "What today smelled like…",
  "A tiny thing that annoyed me, and is already gone…",
  "Something I want to be better at, for us…",
  "The nicest thing anyone did for me today…",
  "A place in our day where I'd like more of you…",
  "Something I'm looking forward to about tomorrow…",
  "A version of us, five years from now…",
  "Something ordinary today that felt quietly good…",
  "A thing I'd like us to try once, just to see…",
  "What I needed today, whether or not I got it…",
  "Something you're better at than you think…",
  "A small promise I'd like to make to you…",
  "The part of today I'd cut out if I could…",
  "Something I noticed that I'd have missed a year ago…",
  "A person I'm glad we have in our lives…",
  "Something about home I want to keep…",
  "What I'd put in a time capsule from today…",
  "A moment I wished you'd been there for…",
  "Something I'm carrying that isn't mine to carry…",
  "The last kind thing I did for myself…",
  "A tradition I'd like us to start…",
  "Something I'm ready to let go of…",
  "What made me feel close to you today…",
  "A thing I'd like you to ask me about…",
  "Something small I want to celebrate…",
  "The way today started, in three words…",
  "Something I keep meaning to do and haven't…",
  "A small change that would make our week better…",
  "Something I appreciated but didn't mention…",
  "What I'd like us to spend more money on…",
  "What I'd like us to spend less time on…",
  "A thing about today I'll have forgotten by Friday…",
  "Something that made me feel taken care of…",
  "A question I don't know the answer to yet…",
  "Something I'd like us to be braver about…",
  "The nicest silence we've shared recently…",
  "Something I'd like to redo from this week…",
  "A small way I could make your tomorrow lighter…",
  "What I'd want a stranger to know about us…",
  "Something today reminded me of, from before we met…",
  "A part of you I'd like to understand better…",
  "Something that felt like too much today…",
  "A small good thing I almost didn't notice…",
  "What I'd like to hear from you this week…",
  "Something I'm hopeful about…",
];

export const solo = [
  "A moment that motivated you today…",
  "Something small you're proud of…",
  "If today were a color, it would be…",
  "Something you want to remember about today…",
  "A song that fit your mood today…",
  "Something you learned about yourself today…",
  "A small win from today…",
  "Something that made you laugh today…",
  "A place you'd love to visit someday…",
  "Something you're looking forward to…",
  "A word that describes today…",
  "Something you'd like to do more of…",
  "A challenge you handled well today…",
  "Something that surprised you today…",
  "A tiny thing that made today feel good…",
  "Something you're glad you said no to…",
  "The first thing you thought about this morning…",
  "Something you did today that your past self would be glad about…",
  "A small kindness you received…",
  "A small kindness you gave…",
  "Something you're avoiding, and why…",
  "The best five minutes of today…",
  "Something you'd tell a friend going through your day…",
  "A thing you're better at than you were a year ago…",
  "Something you noticed that nobody else did…",
  "What your energy was like today, honestly…",
  "Something you want less of this week…",
  "A decision you're glad you made…",
  "Something you're still turning over…",
  "What you needed today…",
  "A person you thought about today…",
  "Something that felt like too much…",
  "The smallest thing that went right…",
  "Something you're curious about right now…",
  "A habit you'd like to start, in one line…",
  "Something you forgave yourself for…",
  "What today would look like as a headline…",
  "Something you're grateful for that costs nothing…",
  "A thing you'd do differently tomorrow…",
  "Something you're quietly working towards…",
  "The last time you felt genuinely rested…",
  "Something you read, saw or heard that stuck…",
  "A worry that turned out to be smaller than it looked…",
  "Something you did just because you wanted to…",
  "What made today different from yesterday…",
  "Something you'd like to be braver about…",
  "A small thing you're looking forward to tomorrow…",
  "Something you're proud of that nobody knows…",
  "What you'd like more room for…",
  "A moment today you felt fully present…",
  "Something you're ready to let go of…",
  "A thing you keep meaning to do…",
  "Something that made you feel capable…",
  "What today taught you, even slightly…",
  "Something you want to protect…",
  "A small pleasure you had today…",
  "Something that drained you…",
  "Something that filled you back up…",
  "What you'd say to yourself this morning, knowing what you know now…",
  "A thing you noticed about your mood…",
  "Something you're looking forward to this month…",
  "A person you'd like to reach out to…",
  "Something you did today that was hard…",
  "What you'd like tomorrow to feel like…",
  "A small change that would help…",
  "Something you're glad is over…",
  "Something you'd happily repeat…",
  "A thing you're curious to try…",
  "What you spent the most time thinking about…",
  "Something you're being too hard on yourself about…",
  "A compliment you'd give yourself today…",
  "Something that surprised you about someone else…",
  "What you'd put on a list of small good things…",
  "A thing you want to remember in a year…",
  "Something you're looking for right now…",
  "What your body was telling you today…",
  "A boundary you'd like to hold…",
  "Something you did well under pressure…",
  "What you'd like to make more time for…",
  "Something you're hopeful about…",
  "A moment you'd like to stretch out…",
  "Something you noticed on the way somewhere…",
  "What felt like progress today, even a little…",
  "A thing you're grateful you have…",
  "Something you'd like to ask someone…",
  "What you're going to do next, in one line…",
  "A small thing you'd like to fix…",
  "Something that felt like yourself today…",
  "What you'd like to be remembered for this week…",
  "Something you're proud you kept going with…",
];

export const quiz = [
  "Who talks more, me or you?",
  "Who's the better cook?",
  "Who falls asleep first?",
  "Who's more likely to forget the time?",
  "Who gives better hugs?",
  "Who's the early bird?",
  "Who's more stubborn?",
  "Who plans better surprises?",
  "Who's the better dancer?",
  "Who laughs more easily?",
  "Who's more likely to cry at a movie?",
  "Who's the better driver?",
  "Who's more organized?",
  "Who's more likely to lose their phone?",
  "Who's the better singer?",
  "Who's more romantic?",
  "Who's more adventurous?",
  "Who's more likely to apologize first?",
  "Who's better with money?",
  "Who's more competitive?",
  "Who's the better listener?",
  "Who's more likely to nap on the couch?",
  "Who takes longer to get ready?",
  "Who's more likely to try a weird new food?",
  "Who's better at keeping secrets?",
  "Who's more likely to start a pillow fight?",
  "Who's the better gift-giver?",
  "Who's more patient?",
  "Who's more likely to remember an anniversary?",
  "Who's the bigger dreamer?",
  "Who texts back faster?",
  "Who's more likely to get lost?",
  "Who's the better packer?",
  "Who complains about the temperature more?",
  "Who's more likely to book the whole trip?",
  "Who takes more photos?",
  "Who's better at saying sorry properly?",
  "Who's more likely to eat the last slice?",
  "Who's the tidier one?",
  "Who's more likely to sing in the shower?",
  "Who worries more?",
  "Who's better at small talk?",
  "Who's more likely to make a new friend at a party?",
  "Who's the better problem-solver?",
  "Who's more likely to stay up too late?",
  "Who's better at remembering names?",
  "Who's more likely to cancel plans?",
  "Who's the more honest one?",
  "Who's better at giving advice?",
  "Who's more likely to cry happy tears?",
  "Who's more likely to be running late?",
  "Who's better at keeping plants alive?",
  "Who's the pickier eater?",
  "Who's more likely to start a project and not finish it?",
  "Who's the better negotiator?",
  "Who spends longer choosing what to watch?",
  "Who's more likely to talk to a stranger's dog?",
  "Who's better in an emergency?",
  "Who's more likely to reread a favourite book?",
  "Who's the louder one?",
  "Who's more likely to take a detour for a view?",
  "Who's better at keeping a routine?",
  "Who's more likely to forget where they parked?",
  "Who's the more sentimental one?",
  "Who's better at surprises on a budget?",
  "Who's more likely to fix something themselves?",
  "Who's better at apologising without being asked?",
  "Who's more likely to fall for a scam email?",
  "Who's the better teacher?",
  "Who's more likely to hold a grudge?",
  "Who's better at waiting?",
  "Who's more likely to change the plan last minute?",
  "Who's the more curious one?",
  "Who's better at reading the room?",
  "Who's more likely to sleep through an alarm?",
  "Who's the more generous one?",
  "Who's better at keeping calm?",
  "Who's more likely to want dessert?",
  "Who's better at remembering what the other said?",
  "Who's more likely to start dancing first?",
  "Who's more likely to take a risk?",
  "Who's better at doing nothing?",
  "Who's more likely to call instead of text?",
  "Who's the more hopeful one?",
  "Who's better at ending an argument?",
  "Who's more likely to plan for the worst?",
  "Who's better at making the other laugh?",
  "Who's more likely to say \"I love you\" first?",
  "Who's the better travel companion?",
  "Who's more likely to remember today, a year from now?",
];
