/* Contenido diario en español. 90 de cada uno. */

export const pair = [
  "Algo pequeño que hoy me hizo sonreír…",
  "Algo que me encantaría que hiciéramos juntos este mes…",
  "Si hoy fuera una foto, sería…",
  "Algo que hiciste hace poco y que te agradezco…",
  "Una canción que hoy me recordó a ti…",
  "Algo que quiero decirte y aún no te he dicho…",
  "Mi momento favorito de hoy, en una frase…",
  "Algo pequeño que haces y que no te digo suficiente cuánto me gusta…",
  "Un lugar al que me encantaría ir contigo algún día…",
  "Algo que aprendí sobre mí hoy…",
  "Si pudiera repetir una hora de hoy, sería…",
  "Una cosita que espero con ganas esta semana…",
  "Algo que me hizo pensar en \"nosotros\"…",
  "Una palabra que describe hoy…",
  "Algo que ojalá hubiera dicho en voz alta hoy…",
  "Un recuerdo nuestro que acaba de hacerme sonreír…",
  "Algo de lo que estoy orgulloso/a de ti…",
  "Una cosita que podrías hacer y que me alegraría el día…",
  "Algo que noté de ti hoy…",
  "Si hoy tuviera banda sonora, sería…",
  "Una pregunta que llevo tiempo queriendo hacerte…",
  "Algo que hoy se sintió como \"hogar\"…",
  "Una pequeña aventura que me gustaría vivir contigo…",
  "Algo de nosotros por lo que estoy agradecido/a…",
  "Un momento de hoy que quiero recordar…",
  "Algo que me da curiosidad sobre ti…",
  "Una pequeña amabilidad que noté hoy…",
  "Algo que hizo el día más ligero…",
  "Un sueño que tuve (para nosotros) sobre el futuro…",
  "Algo que me gustaría tener más, entre nosotros…",
  "La última vez que me hiciste reír a carcajadas…",
  "Algo que querría que supieras si hoy fuera el único día…",
  "Una costumbre tuya que en silencio he llegado a adorar…",
  "Algo que hoy me costó y no dije…",
  "La cosa más pequeña que salió bien hoy…",
  "Una comida que me gustaría cocinar (o comer) contigo…",
  "Algo de hoy que repetiría encantado/a mañana…",
  "Una forma en que me hiciste el día más fácil sin proponértelo…",
  "Algo de antes en lo que sigo pensando…",
  "Cómo me gustaría que fuera nuestro próximo sábado libre…",
  "Una foto nuestra en la que pensé hoy…",
  "Algo que quiero que dejemos de hacer con prisa…",
  "El momento de hoy en que más me sentí yo…",
  "Algo concreto por lo que quiero darte las gracias…",
  "Una preocupación pequeña que prefiero soltar que guardar…",
  "Algo que dijiste una vez y que todavía llevo conmigo…",
  "A qué olía hoy…",
  "Una cosita que me molestó y que ya se me pasó…",
  "Algo en lo que quiero mejorar, por nosotros…",
  "Lo más bonito que alguien hizo por mí hoy…",
  "Un rato del día en el que me gustaría tenerte más cerca…",
  "Algo de mañana que espero con ganas…",
  "Una versión de nosotros dentro de cinco años…",
  "Algo corriente de hoy que se sintió bien en silencio…",
  "Algo que me gustaría que probáramos una vez, solo por ver…",
  "Lo que necesitaba hoy, lo tuviera o no…",
  "Algo que se te da mejor de lo que crees…",
  "Una pequeña promesa que quiero hacerte…",
  "La parte de hoy que quitaría si pudiera…",
  "Algo que noté y que hace un año se me habría escapado…",
  "Una persona que me alegra tener en nuestra vida…",
  "Algo de casa que quiero conservar…",
  "Lo que metería hoy en una cápsula del tiempo…",
  "Un momento en el que ojalá hubieras estado…",
  "Algo que cargo y que no me toca cargar…",
  "Lo último amable que hice por mí…",
  "Una tradición que me gustaría empezar contigo…",
  "Algo que ya estoy listo/a para soltar…",
  "Lo que hoy me hizo sentir cerca de ti…",
  "Algo sobre lo que me gustaría que me preguntaras…",
  "Algo pequeño que quiero celebrar…",
  "Cómo empezó hoy, en tres palabras…",
  "Algo que siempre pienso hacer y nunca hago…",
  "Un cambio pequeño que mejoraría nuestra semana…",
  "Algo que agradecí pero no mencioné…",
  "En qué me gustaría que gastáramos más…",
  "En qué me gustaría que perdiéramos menos tiempo…",
  "Algo de hoy que habré olvidado el viernes…",
  "Algo que me hizo sentir cuidado/a…",
  "Una pregunta cuya respuesta todavía no sé…",
  "Algo en lo que me gustaría que fuéramos más valientes…",
  "El silencio más bonito que hemos compartido últimamente…",
  "Algo de esta semana que repetiría distinto…",
  "Una forma pequeña de hacerte más ligero el mañana…",
  "Lo que querría que un desconocido supiera de nosotros…",
  "Algo que hoy me recordó a antes de conocerte…",
  "Una parte de ti que me gustaría entender mejor…",
  "Algo que hoy se sintió demasiado…",
  "Una cosa buena y pequeña que casi no noto…",
  "Lo que me gustaría oírte decir esta semana…",
  "Algo que me da esperanza…",
];

export const solo = [
  "Un momento que hoy te dio impulso…",
  "Algo pequeño de lo que estás orgulloso/a…",
  "Si hoy fuera un color, sería…",
  "Algo de hoy que quieres recordar…",
  "Una canción que encajó con tu ánimo hoy…",
  "Algo que aprendiste sobre ti hoy…",
  "Una pequeña victoria de hoy…",
  "Algo que te hizo reír hoy…",
  "Un lugar que te encantaría visitar algún día…",
  "Algo que esperas con ganas…",
  "Una palabra que describe hoy…",
  "Algo que te gustaría hacer más…",
  "Un reto que manejaste bien hoy…",
  "Algo que te sorprendió hoy…",
  "Una cosita que hizo que hoy se sintiera bien…",
  "Algo a lo que te alegras de haber dicho que no…",
  "Lo primero que pensaste esta mañana…",
  "Algo que hiciste hoy y que alegraría a quien fuiste antes…",
  "Una pequeña amabilidad que recibiste…",
  "Una pequeña amabilidad que diste…",
  "Algo que estás evitando, y por qué…",
  "Los mejores cinco minutos de hoy…",
  "Lo que le dirías a una amiga que viviera tu día…",
  "Algo que se te da mejor que hace un año…",
  "Algo que notaste y nadie más vio…",
  "Cómo estuvo tu energía hoy, con sinceridad…",
  "Algo que quieres menos esta semana…",
  "Una decisión que te alegra haber tomado…",
  "Algo que sigues dándole vueltas…",
  "Lo que necesitabas hoy…",
  "Una persona en la que pensaste hoy…",
  "Algo que se sintió demasiado…",
  "La cosa más pequeña que salió bien…",
  "Algo que te da curiosidad ahora mismo…",
  "Un hábito que te gustaría empezar, en una línea…",
  "Algo que te perdonaste…",
  "Cómo sería hoy en un titular…",
  "Algo que agradeces y que no cuesta nada…",
  "Algo que harías distinto mañana…",
  "Algo hacia lo que trabajas en silencio…",
  "La última vez que te sentiste de verdad descansado/a…",
  "Algo que leíste, viste u oíste y se te quedó…",
  "Una preocupación que resultó menor de lo que parecía…",
  "Algo que hiciste solo porque querías…",
  "Qué hizo hoy distinto de ayer…",
  "Algo en lo que te gustaría ser más valiente…",
  "Algo pequeño que esperas de mañana…",
  "Algo de lo que estás orgulloso/a y nadie sabe…",
  "Para qué te gustaría tener más espacio…",
  "Un momento de hoy en que estuviste del todo presente…",
  "Algo que ya estás listo/a para soltar…",
  "Algo que siempre piensas hacer…",
  "Algo que te hizo sentir capaz…",
  "Lo que hoy te enseñó, aunque sea poco…",
  "Algo que quieres proteger…",
  "Un pequeño placer que tuviste hoy…",
  "Algo que te agotó…",
  "Algo que te volvió a llenar…",
  "Lo que le dirías a quien fuiste esta mañana, sabiendo lo que sabes…",
  "Algo que notaste sobre tu ánimo…",
  "Algo que esperas con ganas este mes…",
  "Una persona a la que te gustaría escribir…",
  "Algo difícil que hiciste hoy…",
  "Cómo te gustaría que se sintiera mañana…",
  "Un cambio pequeño que ayudaría…",
  "Algo que te alegra que haya terminado…",
  "Algo que repetirías encantado/a…",
  "Algo que tienes ganas de probar…",
  "En qué pensaste más tiempo…",
  "Algo con lo que estás siendo demasiado duro/a contigo…",
  "Un cumplido que te harías hoy…",
  "Algo que te sorprendió de otra persona…",
  "Qué pondrías en una lista de pequeñas cosas buenas…",
  "Algo que quieres recordar dentro de un año…",
  "Algo que estás buscando ahora mismo…",
  "Lo que tu cuerpo te decía hoy…",
  "Un límite que te gustaría sostener…",
  "Algo que hiciste bien bajo presión…",
  "Para qué te gustaría hacer más tiempo…",
  "Algo que te da esperanza…",
  "Un momento que te gustaría alargar…",
  "Algo que notaste yendo de camino a algún sitio…",
  "Qué se sintió como avance hoy, aunque fuera poco…",
  "Algo que agradeces tener…",
  "Algo que te gustaría preguntarle a alguien…",
  "Lo que vas a hacer a continuación, en una línea…",
  "Algo pequeño que te gustaría arreglar…",
  "Algo que hoy se sintió como tú…",
  "Cómo te gustaría que recordaran tu semana…",
  "Algo con lo que te enorgullece haber seguido…",
];

export const quiz = [
  "¿Quién habla más, tú o yo?",
  "¿Quién cocina mejor?",
  "¿Quién se duerme primero?",
  "¿Quién pierde más la noción del tiempo?",
  "¿Quién abraza mejor?",
  "¿Quién madruga más?",
  "¿Quién es más terco/a?",
  "¿Quién planea mejores sorpresas?",
  "¿Quién baila mejor?",
  "¿Quién se ríe más fácilmente?",
  "¿Quién llora más con las películas?",
  "¿Quién conduce mejor?",
  "¿Quién es más organizado/a?",
  "¿Quién pierde más el móvil?",
  "¿Quién canta mejor?",
  "¿Quién es más romántico/a?",
  "¿Quién es más aventurero/a?",
  "¿Quién pide perdón primero?",
  "¿Quién lleva mejor el dinero?",
  "¿Quién es más competitivo/a?",
  "¿Quién escucha mejor?",
  "¿Quién se duerme antes en el sofá?",
  "¿Quién tarda más en arreglarse?",
  "¿Quién prueba antes una comida rara?",
  "¿Quién guarda mejor un secreto?",
  "¿Quién empezaría una guerra de almohadas?",
  "¿Quién regala mejor?",
  "¿Quién es más paciente?",
  "¿Quién se acuerda del aniversario?",
  "¿Quién sueña más despierto/a?",
  "¿Quién contesta más rápido?",
  "¿Quién se pierde más?",
  "¿Quién hace mejor la maleta?",
  "¿Quién se queja más del frío o del calor?",
  "¿Quién organiza el viaje entero?",
  "¿Quién hace más fotos?",
  "¿Quién sabe pedir perdón de verdad?",
  "¿Quién se come el último trozo?",
  "¿Quién es más ordenado/a?",
  "¿Quién canta en la ducha?",
  "¿Quién se preocupa más?",
  "¿Quién habla mejor con desconocidos?",
  "¿Quién hace amigos en una fiesta?",
  "¿Quién resuelve mejor los problemas?",
  "¿Quién se acuesta más tarde?",
  "¿Quién recuerda mejor los nombres?",
  "¿Quién cancela más planes?",
  "¿Quién es más sincero/a?",
  "¿Quién da mejores consejos?",
  "¿Quién llora de alegría más fácil?",
  "¿Quién llega tarde más veces?",
  "¿Quién mantiene vivas las plantas?",
  "¿Quién es más quisquilloso/a con la comida?",
  "¿Quién empieza cosas y no las termina?",
  "¿Quién negocia mejor?",
  "¿Quién tarda más en elegir qué ver?",
  "¿Quién le habla al perro de un desconocido?",
  "¿Quién reacciona mejor en una emergencia?",
  "¿Quién relee sus libros favoritos?",
  "¿Quién habla más alto?",
  "¿Quién se desvía del camino por unas vistas?",
  "¿Quién mantiene mejor una rutina?",
  "¿Quién olvida dónde aparcó?",
  "¿Quién es más sentimental?",
  "¿Quién sorprende mejor con poco dinero?",
  "¿Quién intenta arreglar las cosas solo/a?",
  "¿Quién se disculpa sin que se lo pidan?",
  "¿Quién caería antes en un correo falso?",
  "¿Quién enseña mejor?",
  "¿Quién guarda más rencor?",
  "¿Quién espera mejor?",
  "¿Quién cambia el plan a última hora?",
  "¿Quién es más curioso/a?",
  "¿Quién lee mejor el ambiente?",
  "¿Quién se salta más la alarma?",
  "¿Quién es más generoso/a?",
  "¿Quién mantiene mejor la calma?",
  "¿Quién quiere postre siempre?",
  "¿Quién recuerda mejor lo que dijo el otro?",
  "¿Quién empieza a bailar primero?",
  "¿Quién se arriesga más?",
  "¿Quién sabe mejor no hacer nada?",
  "¿Quién prefiere llamar en vez de escribir?",
  "¿Quién es más optimista?",
  "¿Quién termina mejor una discusión?",
  "¿Quién se prepara para lo peor?",
  "¿Quién hace reír mejor al otro?",
  "¿Quién dice \"te quiero\" primero?",
  "¿Quién es mejor compañero/a de viaje?",
  "¿Quién recordará este día dentro de un año?",
];
