/* Contenu quotidien en français. 90 de chaque. */

export const pair = [
  "Une petite chose qui m'a fait sourire aujourd'hui…",
  "Quelque chose que j'aimerais qu'on fasse ensemble ce mois-ci…",
  "Si aujourd'hui était une image, ce serait…",
  "Quelque chose que tu as fait récemment et dont je te suis reconnaissant(e)…",
  "Une chanson qui m'a fait penser à toi aujourd'hui…",
  "Quelque chose que je veux te dire et que je n'ai pas encore dit…",
  "Mon moment préféré de la journée, en une phrase…",
  "Une petite chose que tu fais et que j'adore sans le dire assez…",
  "Un endroit où j'aimerais aller avec toi un jour…",
  "Quelque chose que j'ai appris sur moi aujourd'hui…",
  "Si je pouvais revivre une heure d'aujourd'hui, ce serait…",
  "Une petite chose que j'attends cette semaine…",
  "Quelque chose qui m'a fait penser à \"nous\"…",
  "Un mot qui décrit aujourd'hui…",
  "Quelque chose que j'aurais aimé dire à voix haute aujourd'hui…",
  "Un souvenir à nous qui vient de me faire sourire…",
  "Quelque chose dont je suis fier/fière pour toi…",
  "Une petite chose que tu pourrais faire et qui illuminerait ma journée…",
  "Quelque chose que j'ai remarqué chez toi aujourd'hui…",
  "Si aujourd'hui avait une bande-son, ce serait…",
  "Une question que j'ai envie de te poser depuis un moment…",
  "Quelque chose qui ressemblait à \"la maison\" aujourd'hui…",
  "Une petite aventure que j'aimerais vivre avec toi…",
  "Quelque chose de nous dont je suis reconnaissant(e)…",
  "Un moment d'aujourd'hui que je veux retenir…",
  "Quelque chose que j'ai envie de savoir sur toi…",
  "Une petite gentillesse que j'ai remarquée aujourd'hui…",
  "Quelque chose qui a rendu la journée plus légère…",
  "Un rêve que j'ai fait (pour nous) sur l'avenir…",
  "Quelque chose dont j'aimerais plus, entre nous…",
  "La dernière fois que tu m'as fait rire aux éclats…",
  "Ce que je voudrais que tu saches si aujourd'hui était le seul jour…",
  "Une habitude à toi que j'ai fini par aimer en silence…",
  "Quelque chose de difficile aujourd'hui, que je n'ai pas dit…",
  "La plus petite chose qui a bien marché aujourd'hui…",
  "Un plat que j'aimerais cuisiner (ou manger) avec toi…",
  "Quelque chose d'aujourd'hui que je referais volontiers demain…",
  "Une façon dont tu m'as facilité la journée sans le vouloir…",
  "Quelque chose de tout à l'heure auquel je pense encore…",
  "À quoi je voudrais que ressemble notre prochain samedi libre…",
  "Une photo de nous à laquelle j'ai pensé aujourd'hui…",
  "Quelque chose qu'on devrait arrêter de faire dans l'urgence…",
  "Le moment d'aujourd'hui où je me suis le plus senti(e) moi-même…",
  "Quelque chose de précis dont je veux te remercier…",
  "Un petit souci que je préfère te confier que garder…",
  "Une phrase que tu as dite un jour et que je garde encore…",
  "L'odeur d'aujourd'hui…",
  "Une petite chose qui m'a agacé(e) et qui est déjà passée…",
  "Quelque chose que je veux mieux faire, pour nous…",
  "La plus jolie chose que quelqu'un a faite pour moi aujourd'hui…",
  "Un moment de la journée où j'aimerais t'avoir plus près…",
  "Quelque chose que j'attends de demain…",
  "Une version de nous dans cinq ans…",
  "Quelque chose d'ordinaire aujourd'hui qui faisait discrètement du bien…",
  "Quelque chose qu'on pourrait essayer une fois, juste pour voir…",
  "Ce dont j'avais besoin aujourd'hui, que je l'aie eu ou non…",
  "Quelque chose où tu es meilleur(e) que tu ne le crois…",
  "Une petite promesse que j'ai envie de te faire…",
  "La partie d'aujourd'hui que je couperais si je pouvais…",
  "Quelque chose que j'ai remarqué et que j'aurais manqué il y a un an…",
  "Une personne que je suis content(e) d'avoir dans nos vies…",
  "Quelque chose de chez nous que je veux garder…",
  "Ce que je mettrais dans une capsule temporelle d'aujourd'hui…",
  "Un moment où j'aurais aimé que tu sois là…",
  "Quelque chose que je porte et qui n'est pas à moi…",
  "La dernière chose gentille que j'ai faite pour moi…",
  "Une tradition que j'aimerais qu'on commence…",
  "Quelque chose que je suis prêt(e) à lâcher…",
  "Ce qui m'a fait me sentir proche de toi aujourd'hui…",
  "Une chose sur laquelle j'aimerais que tu me poses des questions…",
  "Une petite chose que j'ai envie de fêter…",
  "Le début de la journée, en trois mots…",
  "Quelque chose que je veux faire depuis toujours et que je ne fais pas…",
  "Un petit changement qui améliorerait notre semaine…",
  "Quelque chose que j'ai apprécié sans le dire…",
  "Ce pour quoi j'aimerais qu'on dépense plus…",
  "Ce à quoi j'aimerais qu'on passe moins de temps…",
  "Une chose d'aujourd'hui que j'aurai oubliée vendredi…",
  "Quelque chose qui m'a fait me sentir entouré(e)…",
  "Une question dont je n'ai pas encore la réponse…",
  "Quelque chose où j'aimerais qu'on soit plus courageux…",
  "Le plus beau silence qu'on ait partagé récemment…",
  "Quelque chose de cette semaine que je referais autrement…",
  "Une petite façon d'alléger ton lendemain…",
  "Ce que j'aimerais qu'un inconnu sache de nous…",
  "Quelque chose qu'aujourd'hui m'a rappelé, d'avant notre rencontre…",
  "Une part de toi que j'aimerais mieux comprendre…",
  "Quelque chose qui a fait beaucoup aujourd'hui…",
  "Une petite bonne chose que j'ai failli ne pas voir…",
  "Ce que j'aimerais t'entendre dire cette semaine…",
  "Quelque chose qui me donne de l'espoir…",
];

export const solo = [
  "Un moment qui t'a motivé(e) aujourd'hui…",
  "Une petite chose dont tu es fier/fière…",
  "Si aujourd'hui était une couleur, ce serait…",
  "Quelque chose d'aujourd'hui que tu veux retenir…",
  "Une chanson qui collait à ton humeur aujourd'hui…",
  "Quelque chose que tu as appris sur toi aujourd'hui…",
  "Une petite victoire d'aujourd'hui…",
  "Quelque chose qui t'a fait rire aujourd'hui…",
  "Un endroit que tu aimerais visiter un jour…",
  "Quelque chose que tu attends avec impatience…",
  "Un mot qui décrit aujourd'hui…",
  "Quelque chose que tu aimerais faire plus souvent…",
  "Un défi que tu as bien géré aujourd'hui…",
  "Quelque chose qui t'a surpris(e) aujourd'hui…",
  "Une petite chose qui a rendu la journée agréable…",
  "Quelque chose à quoi tu es content(e) d'avoir dit non…",
  "La première chose à laquelle tu as pensé ce matin…",
  "Quelque chose fait aujourd'hui dont ton toi d'avant serait content…",
  "Une petite gentillesse que tu as reçue…",
  "Une petite gentillesse que tu as offerte…",
  "Quelque chose que tu évites, et pourquoi…",
  "Les cinq meilleures minutes d'aujourd'hui…",
  "Ce que tu dirais à un(e) ami(e) qui aurait vécu ta journée…",
  "Quelque chose que tu réussis mieux qu'il y a un an…",
  "Quelque chose que tu as remarqué et que personne n'a vu…",
  "Ton niveau d'énergie aujourd'hui, honnêtement…",
  "Quelque chose dont tu veux moins cette semaine…",
  "Une décision que tu es content(e) d'avoir prise…",
  "Quelque chose que tu retournes encore dans ta tête…",
  "Ce dont tu avais besoin aujourd'hui…",
  "Une personne à laquelle tu as pensé aujourd'hui…",
  "Quelque chose qui a fait beaucoup…",
  "La plus petite chose qui a bien marché…",
  "Quelque chose qui t'intrigue en ce moment…",
  "Une habitude que tu aimerais prendre, en une ligne…",
  "Quelque chose que tu t'es pardonné…",
  "Aujourd'hui, en titre de journal…",
  "Quelque chose de gratuit dont tu es reconnaissant(e)…",
  "Quelque chose que tu ferais autrement demain…",
  "Quelque chose vers quoi tu avances en silence…",
  "La dernière fois que tu t'es senti(e) vraiment reposé(e)…",
  "Quelque chose de lu, vu ou entendu qui est resté…",
  "Un souci plus petit qu'il n'en avait l'air…",
  "Quelque chose que tu as fait juste parce que tu en avais envie…",
  "Ce qui a rendu aujourd'hui différent d'hier…",
  "Quelque chose où tu aimerais être plus courageux/se…",
  "Une petite chose que tu attends de demain…",
  "Quelque chose dont tu es fier/fière et que personne ne sait…",
  "Ce pour quoi tu aimerais plus de place…",
  "Un moment d'aujourd'hui où tu étais pleinement là…",
  "Quelque chose que tu es prêt(e) à lâcher…",
  "Quelque chose que tu veux faire depuis longtemps…",
  "Quelque chose qui t'a fait te sentir capable…",
  "Ce qu'aujourd'hui t'a appris, même un peu…",
  "Quelque chose que tu veux protéger…",
  "Un petit plaisir d'aujourd'hui…",
  "Quelque chose qui t'a vidé(e)…",
  "Quelque chose qui t'a rempli(e) à nouveau…",
  "Ce que tu dirais à toi de ce matin, avec ce que tu sais maintenant…",
  "Quelque chose que tu as remarqué sur ton humeur…",
  "Quelque chose que tu attends ce mois-ci…",
  "Une personne à qui tu aimerais écrire…",
  "Quelque chose de difficile que tu as fait aujourd'hui…",
  "Ce à quoi tu aimerais que demain ressemble…",
  "Un petit changement qui aiderait…",
  "Quelque chose dont tu es content(e) que ce soit fini…",
  "Quelque chose que tu referais volontiers…",
  "Quelque chose que tu as envie d'essayer…",
  "Ce à quoi tu as le plus pensé…",
  "Quelque chose pour lequel tu es trop dur(e) avec toi…",
  "Un compliment que tu te ferais aujourd'hui…",
  "Quelque chose qui t'a surpris(e) chez quelqu'un…",
  "Ce que tu mettrais sur une liste de petites bonnes choses…",
  "Quelque chose que tu veux te rappeler dans un an…",
  "Ce que tu cherches en ce moment…",
  "Ce que ton corps te disait aujourd'hui…",
  "Une limite que tu aimerais tenir…",
  "Quelque chose que tu as bien fait sous pression…",
  "Ce pour quoi tu aimerais dégager plus de temps…",
  "Quelque chose qui te donne de l'espoir…",
  "Un moment que tu aimerais faire durer…",
  "Quelque chose remarqué en chemin quelque part…",
  "Ce qui a ressemblé à un progrès aujourd'hui, même petit…",
  "Quelque chose que tu es content(e) d'avoir…",
  "Une question que tu aimerais poser à quelqu'un…",
  "Ce que tu vas faire ensuite, en une ligne…",
  "Une petite chose que tu aimerais réparer…",
  "Quelque chose qui te ressemblait aujourd'hui…",
  "Ce pour quoi tu aimerais qu'on retienne ta semaine…",
  "Quelque chose que tu es fier/fière d'avoir continué…",
];

export const quiz = [
  "Qui parle le plus, toi ou moi ?",
  "Qui cuisine le mieux ?",
  "Qui s'endort en premier ?",
  "Qui oublie l'heure le plus souvent ?",
  "Qui fait les meilleurs câlins ?",
  "Qui se lève le plus tôt ?",
  "Qui est le/la plus têtu(e) ?",
  "Qui prépare les meilleures surprises ?",
  "Qui danse le mieux ?",
  "Qui rit le plus facilement ?",
  "Qui pleure le plus devant un film ?",
  "Qui conduit le mieux ?",
  "Qui est le/la plus organisé(e) ?",
  "Qui perd le plus souvent son téléphone ?",
  "Qui chante le mieux ?",
  "Qui est le/la plus romantique ?",
  "Qui est le/la plus aventurier(ère) ?",
  "Qui s'excuse en premier ?",
  "Qui gère le mieux l'argent ?",
  "Qui est le/la plus compétitif(ve) ?",
  "Qui écoute le mieux ?",
  "Qui s'endort le plus sur le canapé ?",
  "Qui met le plus de temps à se préparer ?",
  "Qui goûte le plus volontiers un plat bizarre ?",
  "Qui garde le mieux un secret ?",
  "Qui lancerait une bataille d'oreillers ?",
  "Qui offre les meilleurs cadeaux ?",
  "Qui est le/la plus patient(e) ?",
  "Qui se souvient de l'anniversaire ?",
  "Qui rêve le plus ?",
  "Qui répond le plus vite ?",
  "Qui se perd le plus ?",
  "Qui fait le mieux les valises ?",
  "Qui se plaint le plus du chaud ou du froid ?",
  "Qui organise tout le voyage ?",
  "Qui prend le plus de photos ?",
  "Qui sait vraiment s'excuser ?",
  "Qui mange la dernière part ?",
  "Qui est le/la plus rangé(e) ?",
  "Qui chante sous la douche ?",
  "Qui s'inquiète le plus ?",
  "Qui fait le mieux la conversation ?",
  "Qui se fait un(e) ami(e) à une fête ?",
  "Qui résout le mieux les problèmes ?",
  "Qui se couche le plus tard ?",
  "Qui retient le mieux les prénoms ?",
  "Qui annule le plus souvent ?",
  "Qui est le/la plus honnête ?",
  "Qui donne les meilleurs conseils ?",
  "Qui pleure de joie le plus facilement ?",
  "Qui est le plus souvent en retard ?",
  "Qui garde les plantes en vie ?",
  "Qui est le/la plus difficile à table ?",
  "Qui commence des projets sans les finir ?",
  "Qui négocie le mieux ?",
  "Qui met le plus de temps à choisir un film ?",
  "Qui parle au chien d'un inconnu ?",
  "Qui gère le mieux une urgence ?",
  "Qui relit ses livres préférés ?",
  "Qui parle le plus fort ?",
  "Qui fait un détour pour la vue ?",
  "Qui tient le mieux une routine ?",
  "Qui oublie où il/elle s'est garé(e) ?",
  "Qui est le/la plus sentimental(e) ?",
  "Qui fait les meilleures surprises sans budget ?",
  "Qui essaie de réparer les choses seul(e) ?",
  "Qui s'excuse sans qu'on le lui demande ?",
  "Qui tomberait dans le panneau d'un mail douteux ?",
  "Qui explique le mieux ?",
  "Qui garde le plus rancune ?",
  "Qui sait le mieux attendre ?",
  "Qui change de plan à la dernière minute ?",
  "Qui est le/la plus curieux(se) ?",
  "Qui lit le mieux l'ambiance ?",
  "Qui n'entend pas son réveil ?",
  "Qui est le/la plus généreux(se) ?",
  "Qui garde le mieux son calme ?",
  "Qui veut toujours un dessert ?",
  "Qui retient le mieux ce que l'autre a dit ?",
  "Qui se met à danser en premier ?",
  "Qui prend le plus de risques ?",
  "Qui sait le mieux ne rien faire ?",
  "Qui préfère appeler plutôt qu'écrire ?",
  "Qui est le/la plus optimiste ?",
  "Qui met fin à une dispute le mieux ?",
  "Qui prévoit le pire ?",
  "Qui fait le mieux rire l'autre ?",
  "Qui dit \"je t'aime\" en premier ?",
  "Qui est le/la meilleur(e) compagnon de voyage ?",
  "Qui se souviendra de ce jour dans un an ?",
];
