/* Konten harian dalam bahasa Indonesia. Pertanyaan yang sama, dalam urutan yang
   sama, dengan en.js — dailyContent.js bergantung pada urutan itu untuk
   menampilkan pertanyaan suatu hari dalam bahasa yang sedang dipakai. */

export const pair = [
  "Hal kecil yang bikin aku tersenyum hari ini…",
  "Sesuatu yang ingin sekali kita lakukan bersama bulan ini…",
  "Kalau hari ini sebuah gambar, gambarnya…",
  "Sesuatu yang kamu lakukan belakangan ini dan aku syukuri…",
  "Lagu yang mengingatkanku padamu hari ini…",
  "Sesuatu yang ingin kukatakan padamu tapi belum sempat…",
  "Momen favoritku hari ini, dalam satu kalimat…",
  "Hal kecil yang kamu lakukan dan jarang kubilang betapa aku menyukainya…",
  "Tempat yang ingin kudatangi bersamamu suatu hari nanti…",
  "Sesuatu yang kupelajari tentang diriku hari ini…",
  "Kalau bisa mengulang satu jam dari hari ini, aku pilih…",
  "Hal kecil yang kutunggu-tunggu minggu ini…",
  "Sesuatu yang membuatku teringat “kita”…",
  "Satu kata yang menggambarkan hari ini…",
  "Sesuatu yang seharusnya kuucapkan hari ini…",
  "Kenangan kita yang barusan bikin aku tersenyum…",
  "Sesuatu darimu yang membuatku bangga…",
  "Hal kecil yang bisa kamu lakukan dan bikin hariku menyenangkan…",
  "Sesuatu yang kuperhatikan darimu hari ini…",
  "Kalau hari ini punya lagu latar, lagunya…",
  "Pertanyaan yang sudah lama ingin kutanyakan padamu…",
  "Sesuatu yang terasa seperti “rumah” hari ini…",
  "Petualangan kecil yang ingin kita jalani…",
  "Sesuatu tentang kita yang aku syukuri…",
  "Momen hari ini yang ingin kuingat…",
  "Sesuatu tentangmu yang bikin aku penasaran…",
  "Kebaikan kecil yang kuperhatikan hari ini…",
  "Sesuatu yang membuat hari ini terasa lebih ringan…",
  "Mimpiku (untuk kita) tentang masa depan…",
  "Sesuatu yang ingin lebih banyak ada di antara kita…",
  "Terakhir kali kamu bikin aku tertawa lepas…",
  "Sesuatu yang ingin kamu tahu seandainya hari ini satu-satunya hari…",
  "Kebiasaanmu yang diam-diam jadi kusukai…",
  "Sesuatu yang terasa berat hari ini dan tidak kuceritakan…",
  "Hal terkecil yang berjalan lancar hari ini…",
  "Makanan yang ingin kubuat (atau kumakan) bersamamu…",
  "Sesuatu dari hari ini yang mau kuulang lagi besok…",
  "Caramu membuat hariku lebih mudah tanpa sengaja…",
  "Sesuatu yang masih kupikirkan sejak tadi…",
  "Seperti apa hari Sabtu kosong kita berikutnya yang kuinginkan…",
  "Foto kita yang terlintas di pikiranku hari ini…",
  "Sesuatu yang ingin kita jalani tanpa terburu-buru lagi…",
  "Momen hari ini saat aku paling merasa jadi diriku sendiri…",
  "Sesuatu yang ingin kuucapkan terima kasih padamu, secara khusus…",
  "Kekhawatiran kecil yang lebih baik kubagi daripada kupendam…",
  "Sesuatu yang pernah kamu katakan dan masih kubawa sampai sekarang…",
  "Seperti apa aroma hari ini…",
  "Hal kecil yang bikin aku kesal, dan sudah berlalu…",
  "Sesuatu yang ingin kuperbaiki dari diriku, demi kita…",
  "Hal terbaik yang dilakukan seseorang untukku hari ini…",
  "Bagian dari hari kita saat aku ingin lebih banyak bersamamu…",
  "Sesuatu yang kutunggu-tunggu besok…",
  "Gambaran kita, lima tahun dari sekarang…",
  "Hal biasa hari ini yang diam-diam terasa menyenangkan…",
  "Sesuatu yang ingin kita coba sekali saja, sekadar ingin tahu…",
  "Yang kubutuhkan hari ini, entah kudapat atau tidak…",
  "Sesuatu yang kamu kuasai lebih baik dari yang kamu kira…",
  "Janji kecil yang ingin kubuat untukmu…",
  "Bagian hari ini yang ingin kupotong kalau bisa…",
  "Sesuatu yang kusadari, yang setahun lalu pasti terlewat…",
  "Seseorang yang aku syukuri ada dalam hidup kita…",
  "Sesuatu tentang rumah yang ingin kupertahankan…",
  "Yang akan kumasukkan ke kapsul waktu dari hari ini…",
  "Momen saat aku berharap kamu ada di sana…",
  "Sesuatu yang kupikul padahal bukan bebanku…",
  "Hal baik terakhir yang kulakukan untuk diriku sendiri…",
  "Tradisi yang ingin kita mulai…",
  "Sesuatu yang siap kulepaskan…",
  "Yang membuatku merasa dekat denganmu hari ini…",
  "Sesuatu yang ingin kamu tanyakan padaku…",
  "Hal kecil yang ingin kurayakan…",
  "Awal hari ini, dalam tiga kata…",
  "Sesuatu yang terus ingin kulakukan tapi belum juga…",
  "Perubahan kecil yang bakal membuat minggu kita lebih baik…",
  "Sesuatu yang kuhargai tapi tidak kusampaikan…",
  "Hal yang ingin kita beri lebih banyak uang…",
  "Hal yang ingin kita kurangi waktunya…",
  "Sesuatu dari hari ini yang pasti sudah kulupa hari Jumat…",
  "Sesuatu yang membuatku merasa diperhatikan…",
  "Pertanyaan yang belum kutahu jawabannya…",
  "Sesuatu yang ingin kita hadapi dengan lebih berani…",
  "Keheningan paling nyaman yang kita bagi belakangan ini…",
  "Sesuatu dari minggu ini yang ingin kuulang…",
  "Cara kecil untuk membuat hari esokmu lebih ringan…",
  "Yang ingin kuceritakan pada orang asing tentang kita…",
  "Sesuatu hari ini yang mengingatkanku pada masa sebelum kita bertemu…",
  "Bagian dari dirimu yang ingin kupahami lebih baik…",
  "Sesuatu yang terasa terlalu berat hari ini…",
  "Hal baik kecil yang hampir tidak kusadari…",
  "Yang ingin kudengar darimu minggu ini…",
  "Sesuatu yang membuatku punya harapan…",
];

export const solo = [
  "Momen yang memotivasimu hari ini…",
  "Hal kecil yang kamu banggakan…",
  "Kalau hari ini sebuah warna, warnanya…",
  "Sesuatu yang ingin kamu ingat dari hari ini…",
  "Lagu yang cocok dengan suasana hatimu hari ini…",
  "Sesuatu yang kamu pelajari tentang dirimu hari ini…",
  "Kemenangan kecil hari ini…",
  "Sesuatu yang bikin kamu tertawa hari ini…",
  "Tempat yang ingin kamu kunjungi suatu hari nanti…",
  "Sesuatu yang kamu tunggu-tunggu…",
  "Satu kata yang menggambarkan hari ini…",
  "Sesuatu yang ingin lebih sering kamu lakukan…",
  "Tantangan yang kamu hadapi dengan baik hari ini…",
  "Sesuatu yang mengejutkanmu hari ini…",
  "Hal kecil yang membuat hari ini terasa menyenangkan…",
  "Sesuatu yang kamu syukuri sudah kamu tolak…",
  "Hal pertama yang kamu pikirkan pagi ini…",
  "Sesuatu yang kamu lakukan hari ini dan bakal disyukuri dirimu yang dulu…",
  "Kebaikan kecil yang kamu terima…",
  "Kebaikan kecil yang kamu berikan…",
  "Sesuatu yang kamu hindari, dan alasannya…",
  "Lima menit terbaik hari ini…",
  "Yang akan kamu katakan pada teman yang menjalani hari sepertimu…",
  "Sesuatu yang kamu kuasai lebih baik dibanding setahun lalu…",
  "Sesuatu yang hanya kamu yang menyadarinya…",
  "Bagaimana energimu hari ini, sejujurnya…",
  "Sesuatu yang ingin kamu kurangi minggu ini…",
  "Keputusan yang kamu syukuri sudah kamu ambil…",
  "Sesuatu yang masih berputar di kepalamu…",
  "Yang kamu butuhkan hari ini…",
  "Seseorang yang kamu pikirkan hari ini…",
  "Sesuatu yang terasa terlalu berat…",
  "Hal terkecil yang berjalan lancar…",
  "Sesuatu yang bikin kamu penasaran sekarang…",
  "Kebiasaan yang ingin kamu mulai, dalam satu baris…",
  "Sesuatu yang sudah kamu maafkan dari dirimu…",
  "Kalau hari ini jadi judul berita, bunyinya…",
  "Sesuatu yang kamu syukuri dan tidak butuh biaya…",
  "Sesuatu yang akan kamu lakukan berbeda besok…",
  "Sesuatu yang diam-diam sedang kamu upayakan…",
  "Terakhir kali kamu merasa benar-benar cukup istirahat…",
  "Sesuatu yang kamu baca, lihat, atau dengar dan membekas…",
  "Kekhawatiran yang ternyata lebih kecil dari kelihatannya…",
  "Sesuatu yang kamu lakukan hanya karena ingin…",
  "Yang membuat hari ini berbeda dari kemarin…",
  "Sesuatu yang ingin kamu hadapi dengan lebih berani…",
  "Hal kecil yang kamu tunggu-tunggu besok…",
  "Sesuatu yang kamu banggakan dan tak seorang pun tahu…",
  "Hal yang ingin kamu beri lebih banyak ruang…",
  "Momen hari ini saat kamu benar-benar hadir…",
  "Sesuatu yang siap kamu lepaskan…",
  "Sesuatu yang terus ingin kamu lakukan…",
  "Sesuatu yang membuatmu merasa mampu…",
  "Yang diajarkan hari ini padamu, walau sedikit…",
  "Sesuatu yang ingin kamu jaga…",
  "Kesenangan kecil yang kamu rasakan hari ini…",
  "Sesuatu yang menguras tenagamu…",
  "Sesuatu yang mengisi tenagamu lagi…",
  "Yang akan kamu katakan pada dirimu tadi pagi, setelah tahu apa yang kamu tahu sekarang…",
  "Sesuatu yang kamu sadari tentang suasana hatimu…",
  "Sesuatu yang kamu tunggu-tunggu bulan ini…",
  "Seseorang yang ingin kamu hubungi…",
  "Hal sulit yang kamu lakukan hari ini…",
  "Kamu ingin besok terasa seperti apa…",
  "Perubahan kecil yang akan membantu…",
  "Sesuatu yang kamu syukuri sudah selesai…",
  "Sesuatu yang dengan senang hati kamu ulangi…",
  "Sesuatu yang ingin kamu coba…",
  "Hal yang paling lama kamu pikirkan…",
  "Sesuatu yang membuatmu terlalu keras pada diri sendiri…",
  "Pujian yang akan kamu berikan untuk dirimu hari ini…",
  "Sesuatu yang mengejutkanmu dari orang lain…",
  "Yang akan kamu masukkan ke daftar hal-hal baik kecil…",
  "Sesuatu yang ingin kamu ingat setahun lagi…",
  "Sesuatu yang sedang kamu cari sekarang…",
  "Yang dikatakan tubuhmu hari ini…",
  "Batasan yang ingin kamu pertahankan…",
  "Sesuatu yang kamu lakukan dengan baik di bawah tekanan…",
  "Hal yang ingin kamu sediakan lebih banyak waktu…",
  "Sesuatu yang membuatmu punya harapan…",
  "Momen yang ingin kamu perpanjang…",
  "Sesuatu yang kamu perhatikan di perjalanan…",
  "Yang terasa seperti kemajuan hari ini, sekecil apa pun…",
  "Sesuatu yang kamu syukuri karena memilikinya…",
  "Sesuatu yang ingin kamu tanyakan pada seseorang…",
  "Yang akan kamu lakukan selanjutnya, dalam satu baris…",
  "Hal kecil yang ingin kamu perbaiki…",
  "Sesuatu yang terasa seperti dirimu sendiri hari ini…",
  "Kamu ingin dikenang sebagai apa minggu ini…",
  "Sesuatu yang kamu banggakan karena terus kamu jalani…",
];

export const quiz = [
  "Siapa yang lebih banyak bicara, aku atau kamu?",
  "Siapa yang lebih jago masak?",
  "Siapa yang tidur duluan?",
  "Siapa yang lebih sering lupa waktu?",
  "Siapa yang pelukannya lebih enak?",
  "Siapa yang bangun lebih pagi?",
  "Siapa yang lebih keras kepala?",
  "Siapa yang lebih jago bikin kejutan?",
  "Siapa yang lebih jago menari?",
  "Siapa yang lebih gampang tertawa?",
  "Siapa yang lebih gampang nangis saat nonton film?",
  "Siapa yang lebih jago menyetir?",
  "Siapa yang lebih rapi dan teratur?",
  "Siapa yang lebih sering kehilangan ponsel?",
  "Siapa yang lebih jago menyanyi?",
  "Siapa yang lebih romantis?",
  "Siapa yang lebih suka bertualang?",
  "Siapa yang minta maaf duluan?",
  "Siapa yang lebih pintar mengatur uang?",
  "Siapa yang lebih kompetitif?",
  "Siapa pendengar yang lebih baik?",
  "Siapa yang lebih sering ketiduran di sofa?",
  "Siapa yang lebih lama bersiap-siap?",
  "Siapa yang lebih berani coba makanan aneh?",
  "Siapa yang lebih pandai menjaga rahasia?",
  "Siapa yang bakal memulai perang bantal?",
  "Siapa yang lebih jago memilih hadiah?",
  "Siapa yang lebih sabar?",
  "Siapa yang lebih ingat hari jadi?",
  "Siapa yang lebih suka bermimpi besar?",
  "Siapa yang lebih cepat membalas pesan?",
  "Siapa yang lebih gampang tersesat?",
  "Siapa yang lebih jago berkemas?",
  "Siapa yang lebih sering mengeluh soal suhu?",
  "Siapa yang biasanya memesan semua urusan liburan?",
  "Siapa yang lebih banyak memotret?",
  "Siapa yang lebih bisa minta maaf dengan tulus?",
  "Siapa yang makan potongan terakhir?",
  "Siapa yang lebih suka kebersihan?",
  "Siapa yang suka nyanyi di kamar mandi?",
  "Siapa yang lebih gampang khawatir?",
  "Siapa yang lebih jago basa-basi?",
  "Siapa yang gampang dapat teman baru di pesta?",
  "Siapa yang lebih jago memecahkan masalah?",
  "Siapa yang lebih sering begadang?",
  "Siapa yang lebih ingat nama orang?",
  "Siapa yang lebih sering membatalkan rencana?",
  "Siapa yang lebih jujur?",
  "Siapa yang lebih jago memberi nasihat?",
  "Siapa yang lebih gampang menangis bahagia?",
  "Siapa yang lebih sering telat?",
  "Siapa yang lebih bisa merawat tanaman?",
  "Siapa yang lebih pilih-pilih makanan?",
  "Siapa yang suka memulai sesuatu tapi tidak selesai?",
  "Siapa yang lebih jago menawar?",
  "Siapa yang lebih lama memilih tontonan?",
  "Siapa yang suka mengajak ngobrol anjing orang lain?",
  "Siapa yang lebih tenang dalam keadaan darurat?",
  "Siapa yang suka membaca ulang buku favorit?",
  "Siapa yang suaranya lebih keras?",
  "Siapa yang rela memutar jalan demi pemandangan?",
  "Siapa yang lebih bisa menjaga rutinitas?",
  "Siapa yang lupa parkir di mana?",
  "Siapa yang lebih sentimental?",
  "Siapa yang lebih jago bikin kejutan hemat?",
  "Siapa yang suka memperbaiki barang sendiri?",
  "Siapa yang minta maaf tanpa diminta?",
  "Siapa yang lebih gampang tertipu email penipuan?",
  "Siapa yang lebih jago mengajar?",
  "Siapa yang lebih suka menyimpan dendam?",
  "Siapa yang lebih sabar menunggu?",
  "Siapa yang suka mengubah rencana di menit terakhir?",
  "Siapa yang lebih penasaran?",
  "Siapa yang lebih peka membaca suasana?",
  "Siapa yang tidak terbangun oleh alarm?",
  "Siapa yang lebih murah hati?",
  "Siapa yang lebih bisa tetap tenang?",
  "Siapa yang selalu mau makanan penutup?",
  "Siapa yang lebih ingat ucapan pasangannya?",
  "Siapa yang mulai menari duluan?",
  "Siapa yang lebih berani ambil risiko?",
  "Siapa yang lebih jago bersantai tanpa melakukan apa-apa?",
  "Siapa yang lebih suka menelepon daripada kirim pesan?",
  "Siapa yang lebih optimis?",
  "Siapa yang lebih jago mengakhiri pertengkaran?",
  "Siapa yang selalu bersiap untuk kemungkinan terburuk?",
  "Siapa yang lebih jago bikin pasangannya tertawa?",
  "Siapa yang bilang “aku sayang kamu” duluan?",
  "Siapa teman perjalanan yang lebih asyik?",
  "Siapa yang masih ingat hari ini setahun lagi?",
];
