/* Contenuti quotidiani in italiano. 90 per lista. */

export const pair = [
  "Una piccola cosa che oggi mi ha fatto sorridere…",
  "Qualcosa che mi piacerebbe fare insieme a te questo mese…",
  "Se oggi fosse una foto, sarebbe…",
  "Qualcosa che hai fatto di recente e di cui ti sono grato/a…",
  "Una canzone che oggi mi ha ricordato te…",
  "Qualcosa che voglio dirti e non ti ho ancora detto…",
  "Il mio momento preferito di oggi, in una frase…",
  "Una piccola cosa che fai e che non ti dico abbastanza quanto amo…",
  "Un posto dove vorrei andare con te un giorno…",
  "Qualcosa che oggi ho imparato su di me…",
  "Se potessi rivivere un'ora di oggi, sarebbe…",
  "Una piccola cosa che aspetto questa settimana…",
  "Qualcosa che mi ha fatto pensare a \"noi\"…",
  "Una parola che descrive oggi…",
  "Qualcosa che oggi avrei voluto dire ad alta voce…",
  "Un nostro ricordo che mi ha appena fatto sorridere…",
  "Qualcosa di te di cui sono fiero/a…",
  "Una piccola cosa che potresti fare e che mi farebbe la giornata…",
  "Qualcosa che oggi ho notato di te…",
  "Se oggi avesse una colonna sonora, sarebbe…",
  "Una domanda che voglio farti da un po'…",
  "Qualcosa che oggi è sembrato \"casa\"…",
  "Una piccola avventura che vorrei vivere con te…",
  "Qualcosa di noi per cui sono grato/a…",
  "Un momento di oggi che voglio ricordare…",
  "Qualcosa che mi incuriosisce di te…",
  "Una piccola gentilezza che ho notato oggi…",
  "Qualcosa che ha reso oggi più leggero…",
  "Un sogno che ho fatto (per noi) sul futuro…",
  "Qualcosa che vorrei di più, tra noi…",
  "L'ultima volta che mi hai fatto ridere forte…",
  "Cosa vorrei che sapessi se oggi fosse l'unico giorno…",
  "Un'abitudine tua che in silenzio ho imparato ad amare…",
  "Qualcosa di difficile oggi, che non ho detto…",
  "La cosa più piccola andata bene oggi…",
  "Un piatto che vorrei cucinare (o mangiare) con te…",
  "Qualcosa di oggi che rifarei volentieri domani…",
  "Un modo in cui mi hai reso la giornata più facile senza volerlo…",
  "Qualcosa di prima a cui sto ancora pensando…",
  "Come vorrei che fosse il nostro prossimo sabato libero…",
  "Una nostra foto a cui ho pensato oggi…",
  "Qualcosa che dovremmo smettere di fare di fretta…",
  "Il momento di oggi in cui mi sono sentito/a più me stesso/a…",
  "Qualcosa di preciso per cui voglio ringraziarti…",
  "Una piccola preoccupazione che preferisco passarti che tenere…",
  "Qualcosa che hai detto una volta e che porto ancora con me…",
  "Di cosa profumava oggi…",
  "Una piccolezza che mi ha infastidito e che è già passata…",
  "Qualcosa in cui voglio migliorare, per noi…",
  "La cosa più bella che qualcuno ha fatto per me oggi…",
  "Un momento della giornata in cui vorrei più te…",
  "Qualcosa che aspetto di domani…",
  "Una versione di noi fra cinque anni…",
  "Qualcosa di ordinario oggi che è stato silenziosamente bello…",
  "Qualcosa che proverei una volta, tanto per vedere…",
  "Ciò di cui avevo bisogno oggi, che l'abbia avuto o no…",
  "Qualcosa in cui sei più bravo/a di quanto credi…",
  "Una piccola promessa che voglio farti…",
  "La parte di oggi che taglierei, se potessi…",
  "Qualcosa che ho notato e che un anno fa mi sarebbe sfuggito…",
  "Una persona che sono contento/a di avere nella nostra vita…",
  "Qualcosa di casa nostra che voglio conservare…",
  "Cosa metterei oggi in una capsula del tempo…",
  "Un momento in cui avrei voluto che ci fossi…",
  "Qualcosa che porto e che non è mio da portare…",
  "L'ultima cosa gentile che ho fatto per me…",
  "Una tradizione che vorrei iniziare con te…",
  "Qualcosa che sono pronto/a a lasciare andare…",
  "Cosa mi ha fatto sentire vicino/a a te oggi…",
  "Qualcosa su cui vorrei che mi facessi domande…",
  "Una piccola cosa che voglio festeggiare…",
  "Com'è iniziato oggi, in tre parole…",
  "Qualcosa che voglio fare da sempre e non faccio mai…",
  "Un piccolo cambiamento che migliorerebbe la nostra settimana…",
  "Qualcosa che ho apprezzato ma non ho detto…",
  "Su cosa vorrei spendessimo di più…",
  "A cosa vorrei dedicassimo meno tempo…",
  "Una cosa di oggi che venerdì avrò dimenticato…",
  "Qualcosa che mi ha fatto sentire accudito/a…",
  "Una domanda di cui non ho ancora la risposta…",
  "Qualcosa su cui vorrei fossimo più coraggiosi…",
  "Il silenzio più bello che abbiamo condiviso di recente…",
  "Qualcosa di questa settimana che rifarei diversamente…",
  "Un piccolo modo per alleggerirti il domani…",
  "Cosa vorrei che uno sconosciuto sapesse di noi…",
  "Qualcosa che oggi mi ha ricordato i tempi prima di noi…",
  "Una parte di te che vorrei capire meglio…",
  "Qualcosa che oggi è sembrato troppo…",
  "Una piccola cosa bella che stavo per non vedere…",
  "Cosa vorrei sentirti dire questa settimana…",
  "Qualcosa che mi dà speranza…",
];

export const solo = [
  "Un momento che oggi ti ha dato la carica…",
  "Una piccola cosa di cui sei fiero/a…",
  "Se oggi fosse un colore, sarebbe…",
  "Qualcosa di oggi che vuoi ricordare…",
  "Una canzone che oggi rispecchiava il tuo umore…",
  "Qualcosa che oggi hai scoperto di te…",
  "Una piccola vittoria di oggi…",
  "Qualcosa che oggi ti ha fatto ridere…",
  "Un posto che vorresti visitare un giorno…",
  "Qualcosa che aspetti con piacere…",
  "Una parola che descrive oggi…",
  "Qualcosa che vorresti fare più spesso…",
  "Una sfida che oggi hai gestito bene…",
  "Qualcosa che oggi ti ha sorpreso…",
  "Una piccolezza che ha reso oggi piacevole…",
  "Qualcosa a cui sei contento/a di aver detto di no…",
  "La prima cosa a cui hai pensato stamattina…",
  "Qualcosa fatto oggi di cui il te di ieri sarebbe contento…",
  "Una piccola gentilezza ricevuta…",
  "Una piccola gentilezza data…",
  "Qualcosa che stai evitando, e perché…",
  "I migliori cinque minuti di oggi…",
  "Cosa diresti a un amico che avesse vissuto la tua giornata…",
  "Qualcosa in cui sei migliorato/a rispetto a un anno fa…",
  "Qualcosa che hai notato e che nessun altro ha visto…",
  "Com'era davvero la tua energia oggi…",
  "Qualcosa di cui vuoi meno questa settimana…",
  "Una decisione che sei contento/a di aver preso…",
  "Qualcosa che stai ancora rimuginando…",
  "Di cosa avevi bisogno oggi…",
  "Una persona a cui hai pensato oggi…",
  "Qualcosa che è sembrato troppo…",
  "La cosa più piccola andata bene…",
  "Qualcosa che ti incuriosisce adesso…",
  "Un'abitudine che vorresti iniziare, in una riga…",
  "Qualcosa che ti sei perdonato/a…",
  "Oggi come titolo di giornale…",
  "Qualcosa di gratuito per cui sei grato/a…",
  "Qualcosa che domani faresti diversamente…",
  "Qualcosa verso cui lavori in silenzio…",
  "L'ultima volta che ti sei sentito/a davvero riposato/a…",
  "Qualcosa letto, visto o sentito che ti è rimasto…",
  "Una preoccupazione più piccola di quanto sembrasse…",
  "Qualcosa fatto solo perché ne avevi voglia…",
  "Cosa ha reso oggi diverso da ieri…",
  "Qualcosa su cui vorresti essere più coraggioso/a…",
  "Una piccola cosa che aspetti da domani…",
  "Qualcosa di cui sei fiero/a e che nessuno sa…",
  "Per cosa vorresti più spazio…",
  "Un momento di oggi in cui eri davvero presente…",
  "Qualcosa che sei pronto/a a lasciare andare…",
  "Qualcosa che ti riprometti sempre di fare…",
  "Qualcosa che ti ha fatto sentire capace…",
  "Cosa ti ha insegnato oggi, anche solo un po'…",
  "Qualcosa che vuoi proteggere…",
  "Un piccolo piacere di oggi…",
  "Qualcosa che ti ha svuotato…",
  "Qualcosa che ti ha riempito di nuovo…",
  "Cosa diresti a te di stamattina, sapendo quello che sai…",
  "Qualcosa che hai notato del tuo umore…",
  "Qualcosa che aspetti questo mese…",
  "Una persona a cui vorresti scrivere…",
  "Qualcosa di difficile che hai fatto oggi…",
  "Come vorresti che fosse domani…",
  "Un piccolo cambiamento che aiuterebbe…",
  "Qualcosa che sei contento/a sia finito…",
  "Qualcosa che rifaresti volentieri…",
  "Qualcosa che hai voglia di provare…",
  "A cosa hai pensato più a lungo…",
  "Qualcosa su cui sei troppo duro/a con te…",
  "Un complimento che ti faresti oggi…",
  "Qualcosa che ti ha sorpreso di qualcun altro…",
  "Cosa metteresti in una lista di piccole cose belle…",
  "Qualcosa che vuoi ricordare fra un anno…",
  "Cosa stai cercando in questo momento…",
  "Cosa ti stava dicendo il corpo oggi…",
  "Un confine che vorresti mantenere…",
  "Qualcosa fatto bene sotto pressione…",
  "Per cosa vorresti trovare più tempo…",
  "Qualcosa che ti dà speranza…",
  "Un momento che vorresti allungare…",
  "Qualcosa notato mentre andavi da qualche parte…",
  "Cosa è sembrato un progresso oggi, anche piccolo…",
  "Qualcosa che sei contento/a di avere…",
  "Qualcosa che vorresti chiedere a qualcuno…",
  "Cosa farai dopo, in una riga…",
  "Una piccola cosa che vorresti sistemare…",
  "Qualcosa che oggi ti somigliava…",
  "Per cosa vorresti che ricordassero la tua settimana…",
  "Qualcosa che sei fiero/a di aver continuato…",
];

export const quiz = [
  "Chi parla di più, tu o io?",
  "Chi cucina meglio?",
  "Chi si addormenta prima?",
  "Chi perde più spesso la cognizione del tempo?",
  "Chi abbraccia meglio?",
  "Chi si sveglia prima?",
  "Chi è più testardo/a?",
  "Chi organizza le sorprese migliori?",
  "Chi balla meglio?",
  "Chi ride più facilmente?",
  "Chi piange di più al cinema?",
  "Chi guida meglio?",
  "Chi è più organizzato/a?",
  "Chi perde più spesso il telefono?",
  "Chi canta meglio?",
  "Chi è più romantico/a?",
  "Chi è più avventuroso/a?",
  "Chi chiede scusa per primo/a?",
  "Chi gestisce meglio i soldi?",
  "Chi è più competitivo/a?",
  "Chi ascolta meglio?",
  "Chi si addormenta sul divano?",
  "Chi ci mette di più a prepararsi?",
  "Chi prova più volentieri un cibo strano?",
  "Chi mantiene meglio un segreto?",
  "Chi comincerebbe una battaglia di cuscini?",
  "Chi fa i regali migliori?",
  "Chi è più paziente?",
  "Chi si ricorda dell'anniversario?",
  "Chi sogna di più?",
  "Chi risponde più in fretta?",
  "Chi si perde più spesso?",
  "Chi fa meglio la valigia?",
  "Chi si lamenta di più del caldo o del freddo?",
  "Chi organizza tutto il viaggio?",
  "Chi fa più foto?",
  "Chi sa scusarsi davvero?",
  "Chi mangia l'ultima fetta?",
  "Chi è più ordinato/a?",
  "Chi canta sotto la doccia?",
  "Chi si preoccupa di più?",
  "Chi è più bravo/a nelle chiacchiere?",
  "Chi fa amicizia a una festa?",
  "Chi risolve meglio i problemi?",
  "Chi fa più tardi la sera?",
  "Chi ricorda meglio i nomi?",
  "Chi annulla più spesso i piani?",
  "Chi è più sincero/a?",
  "Chi dà i consigli migliori?",
  "Chi piange di gioia più facilmente?",
  "Chi è più spesso in ritardo?",
  "Chi tiene in vita le piante?",
  "Chi è più schizzinoso/a a tavola?",
  "Chi inizia cose e non le finisce?",
  "Chi tratta meglio?",
  "Chi ci mette di più a scegliere cosa guardare?",
  "Chi parla al cane di uno sconosciuto?",
  "Chi se la cava meglio in emergenza?",
  "Chi rilegge i libri preferiti?",
  "Chi ha la voce più alta?",
  "Chi fa una deviazione per un bel panorama?",
  "Chi mantiene meglio una routine?",
  "Chi dimentica dove ha parcheggiato?",
  "Chi è più sentimentale?",
  "Chi fa sorprese migliori con pochi soldi?",
  "Chi prova a riparare le cose da solo/a?",
  "Chi si scusa senza che glielo chiedano?",
  "Chi cascherebbe in una mail truffa?",
  "Chi spiega meglio?",
  "Chi porta più rancore?",
  "Chi sa aspettare meglio?",
  "Chi cambia i piani all'ultimo momento?",
  "Chi è più curioso/a?",
  "Chi capisce meglio l'atmosfera?",
  "Chi non sente la sveglia?",
  "Chi è più generoso/a?",
  "Chi resta più calmo/a?",
  "Chi vuole sempre il dolce?",
  "Chi ricorda meglio cosa ha detto l'altro?",
  "Chi inizia a ballare per primo/a?",
  "Chi rischia di più?",
  "Chi è più bravo/a a non fare nulla?",
  "Chi preferisce chiamare invece di scrivere?",
  "Chi è più ottimista?",
  "Chi chiude meglio una discussione?",
  "Chi si prepara al peggio?",
  "Chi fa ridere meglio l'altro?",
  "Chi dice \"ti amo\" per primo/a?",
  "Chi è il/la miglior compagno/a di viaggio?",
  "Chi si ricorderà di oggi fra un anno?",
];
