/* Conteúdo diário em português. Mesmas perguntas, na mesma ordem, que en.js —
   dailyContent.js depende disso para mostrar a pergunta de um dia no idioma atual. */

export const pair = [
  "Uma coisinha que me fez sorrir hoje…",
  "Algo que eu adoraria que fizéssemos juntos este mês…",
  "Se hoje fosse uma imagem, seria…",
  "Algo que você fez recentemente e pelo qual sou grato(a)…",
  "Uma música que me fez lembrar de você hoje…",
  "Algo que quero te contar, mas ainda não contei…",
  "Meu momento favorito de hoje, em uma frase…",
  "Uma coisinha que você faz e que eu não digo o bastante o quanto amo…",
  "Um lugar aonde eu adoraria ir com você um dia…",
  "Algo que aprendi sobre mim hoje…",
  "Se eu pudesse reviver uma hora de hoje, seria…",
  "Uma coisinha que estou esperando com alegria esta semana…",
  "Algo que me fez pensar em “nós”…",
  "Uma palavra que descreve hoje…",
  "Algo que eu queria ter dito em voz alta hoje…",
  "Uma lembrança nossa que me fez sorrir agora…",
  "Algo em você que me enche de orgulho…",
  "Uma coisinha que você poderia fazer e que alegraria meu dia…",
  "Algo que reparei em você hoje…",
  "Se hoje tivesse uma trilha sonora, seria…",
  "Uma pergunta que ando querendo te fazer…",
  "Algo que me deu sensação de “lar” hoje…",
  "Uma pequena aventura que eu queria que vivêssemos…",
  "Algo em nós pelo qual sou grato(a)…",
  "Um momento de hoje que quero guardar…",
  "Algo sobre você que me deixa curioso(a)…",
  "Uma pequena gentileza que notei hoje…",
  "Algo que deixou o dia de hoje mais leve…",
  "Um sonho que tive (para nós) sobre o futuro…",
  "Algo que eu queria ter mais, em nós…",
  "A última vez que você me fez rir alto…",
  "Algo que eu gostaria que você soubesse se hoje fosse o único dia…",
  "Um hábito seu que aprendi a amar em silêncio…",
  "Algo que achei difícil hoje e não falei…",
  "A menor coisa que deu certo hoje…",
  "Uma refeição que eu queria preparar (ou comer) com você…",
  "Algo de hoje que eu faria de novo amanhã com prazer…",
  "Um jeito como você facilitou meu dia sem querer…",
  "Algo em que ainda estou pensando desde mais cedo…",
  "Como eu gostaria que fosse nosso próximo sábado livre…",
  "Uma foto nossa em que pensei hoje…",
  "Algo que eu queria que a gente parasse de fazer com pressa…",
  "O momento de hoje em que mais me senti eu mesmo(a)…",
  "Algo pelo qual quero te agradecer, especificamente…",
  "Uma pequena preocupação que prefiro entregar a carregar…",
  "Algo que você disse uma vez e que ainda carrego comigo…",
  "Que cheiro o dia de hoje teve…",
  "Uma coisinha que me irritou e já passou…",
  "Algo em que quero melhorar, por nós…",
  "A coisa mais legal que alguém fez por mim hoje…",
  "Um momento do nosso dia em que eu queria mais de você…",
  "Algo que estou esperando com alegria para amanhã…",
  "Uma versão de nós daqui a cinco anos…",
  "Algo comum de hoje que foi bom, em silêncio…",
  "Uma coisa que eu queria que tentássemos uma vez, só para ver…",
  "O que eu precisava hoje, tendo recebido ou não…",
  "Algo em que você é melhor do que imagina…",
  "Uma pequena promessa que eu queria te fazer…",
  "A parte de hoje que eu cortaria se pudesse…",
  "Algo que notei e que teria passado despercebido há um ano…",
  "Uma pessoa que fico feliz de termos na nossa vida…",
  "Algo da nossa casa que quero manter…",
  "O que eu colocaria numa cápsula do tempo de hoje…",
  "Um momento em que eu queria que você estivesse lá…",
  "Algo que estou carregando e que não é meu…",
  "A última coisa gentil que fiz por mim…",
  "Uma tradição que eu queria que começássemos…",
  "Algo que estou pronto(a) para deixar ir…",
  "O que me fez sentir perto de você hoje…",
  "Uma coisa que eu queria que você me perguntasse…",
  "Algo pequeno que quero comemorar…",
  "Como o dia começou, em três palavras…",
  "Algo que vivo querendo fazer e ainda não fiz…",
  "Uma pequena mudança que melhoraria nossa semana…",
  "Algo que valorizei, mas não comentei…",
  "Em que eu queria que gastássemos mais dinheiro…",
  "Em que eu queria que gastássemos menos tempo…",
  "Uma coisa de hoje que já terei esquecido na sexta…",
  "Algo que me fez sentir cuidado(a)…",
  "Uma pergunta para a qual ainda não tenho resposta…",
  "Algo em que eu queria que fôssemos mais corajosos…",
  "O silêncio mais gostoso que dividimos ultimamente…",
  "Algo desta semana que eu queria refazer…",
  "Um jeitinho de deixar seu amanhã mais leve…",
  "O que eu queria que um desconhecido soubesse sobre nós…",
  "Algo que hoje me lembrou de antes de a gente se conhecer…",
  "Uma parte de você que eu queria entender melhor…",
  "Algo que foi demais hoje…",
  "Uma coisinha boa que quase não percebi…",
  "O que eu queria ouvir de você esta semana…",
  "Algo que me dá esperança…",
];

export const solo = [
  "Um momento que te motivou hoje…",
  "Algo pequeno de que você se orgulha…",
  "Se hoje fosse uma cor, seria…",
  "Algo que você quer lembrar de hoje…",
  "Uma música que combinou com seu humor hoje…",
  "Algo que você aprendeu sobre si hoje…",
  "Uma pequena vitória de hoje…",
  "Algo que te fez rir hoje…",
  "Um lugar que você adoraria conhecer um dia…",
  "Algo que você está esperando com alegria…",
  "Uma palavra que descreve hoje…",
  "Algo que você queria fazer mais…",
  "Um desafio que você encarou bem hoje…",
  "Algo que te surpreendeu hoje…",
  "Uma coisinha que deixou o dia bom…",
  "Algo a que você ficou feliz de ter dito não…",
  "A primeira coisa em que você pensou de manhã…",
  "Algo que você fez hoje e que deixaria seu eu do passado feliz…",
  "Uma pequena gentileza que você recebeu…",
  "Uma pequena gentileza que você fez…",
  "Algo que você está evitando, e por quê…",
  "Os melhores cinco minutos de hoje…",
  "Algo que você diria a um amigo que vivesse o seu dia…",
  "Uma coisa em que você é melhor do que há um ano…",
  "Algo que só você percebeu…",
  "Como estava sua energia hoje, de verdade…",
  "Algo que você quer menos esta semana…",
  "Uma decisão que você fica feliz de ter tomado…",
  "Algo que ainda está dando voltas na sua cabeça…",
  "O que você precisava hoje…",
  "Uma pessoa em quem você pensou hoje…",
  "Algo que foi demais…",
  "A menor coisa que deu certo…",
  "Algo que te deixa curioso(a) agora…",
  "Um hábito que você queria começar, em uma linha…",
  "Algo pelo qual você se perdoou…",
  "Como seria o dia de hoje em uma manchete…",
  "Algo pelo qual você é grato(a) e que não custa nada…",
  "Uma coisa que você faria diferente amanhã…",
  "Algo que você está buscando em silêncio…",
  "A última vez que você se sentiu realmente descansado(a)…",
  "Algo que você leu, viu ou ouviu e que ficou…",
  "Uma preocupação que acabou sendo menor do que parecia…",
  "Algo que você fez só porque quis…",
  "O que fez hoje ser diferente de ontem…",
  "Algo em que você queria ter mais coragem…",
  "Uma coisinha que você espera com alegria para amanhã…",
  "Algo de que você se orgulha e que ninguém sabe…",
  "Para o que você queria ter mais espaço…",
  "Um momento de hoje em que você esteve totalmente presente…",
  "Algo que você está pronto(a) para deixar ir…",
  "Uma coisa que você vive querendo fazer…",
  "Algo que te fez se sentir capaz…",
  "O que hoje te ensinou, nem que seja um pouco…",
  "Algo que você quer proteger…",
  "Um pequeno prazer que você teve hoje…",
  "Algo que te esgotou…",
  "Algo que te recarregou…",
  "O que você diria a si mesmo(a) hoje de manhã, sabendo o que sabe agora…",
  "Uma coisa que você notou no seu humor…",
  "Algo que você está esperando com alegria este mês…",
  "Uma pessoa com quem você queria falar…",
  "Algo difícil que você fez hoje…",
  "Como você queria que amanhã fosse…",
  "Uma pequena mudança que ajudaria…",
  "Algo que você fica feliz que tenha acabado…",
  "Algo que você repetiria com prazer…",
  "Uma coisa que você tem curiosidade de experimentar…",
  "Em que você passou mais tempo pensando…",
  "Algo com que você está sendo duro(a) demais consigo…",
  "Um elogio que você se daria hoje…",
  "Algo que te surpreendeu em outra pessoa…",
  "O que você colocaria numa lista de pequenas coisas boas…",
  "Uma coisa que você quer lembrar daqui a um ano…",
  "Algo que você está procurando agora…",
  "O que seu corpo estava te dizendo hoje…",
  "Um limite que você queria manter…",
  "Algo que você fez bem sob pressão…",
  "Para o que você queria arranjar mais tempo…",
  "Algo que te dá esperança…",
  "Um momento que você queria prolongar…",
  "Algo que você notou a caminho de algum lugar…",
  "O que pareceu um avanço hoje, mesmo pequeno…",
  "Uma coisa que você é grato(a) por ter…",
  "Algo que você queria perguntar a alguém…",
  "O que você vai fazer a seguir, em uma linha…",
  "Uma coisinha que você queria consertar…",
  "Algo em que você se sentiu você mesmo(a) hoje…",
  "Pelo que você queria ser lembrado(a) esta semana…",
  "Algo em que você se orgulha de ter continuado…",
];

export const quiz = [
  "Quem fala mais, eu ou você?",
  "Quem cozinha melhor?",
  "Quem dorme primeiro?",
  "Quem perde mais a noção da hora?",
  "Quem dá os melhores abraços?",
  "Quem acorda mais cedo?",
  "Quem é mais teimoso(a)?",
  "Quem planeja as melhores surpresas?",
  "Quem dança melhor?",
  "Quem ri com mais facilidade?",
  "Quem chora mais em filme?",
  "Quem dirige melhor?",
  "Quem é mais organizado(a)?",
  "Quem perde mais o celular?",
  "Quem canta melhor?",
  "Quem é mais romântico(a)?",
  "Quem é mais aventureiro(a)?",
  "Quem pede desculpas primeiro?",
  "Quem lida melhor com dinheiro?",
  "Quem é mais competitivo(a)?",
  "Quem escuta melhor?",
  "Quem cochila mais no sofá?",
  "Quem demora mais para se arrumar?",
  "Quem topa mais provar uma comida estranha?",
  "Quem guarda segredo melhor?",
  "Quem começaria uma guerra de travesseiros?",
  "Quem dá os melhores presentes?",
  "Quem é mais paciente?",
  "Quem lembra mais das datas especiais?",
  "Quem sonha mais alto?",
  "Quem responde mensagem mais rápido?",
  "Quem se perde mais?",
  "Quem faz a mala melhor?",
  "Quem reclama mais da temperatura?",
  "Quem costuma reservar a viagem inteira?",
  "Quem tira mais fotos?",
  "Quem pede desculpas de verdade melhor?",
  "Quem come o último pedaço?",
  "Quem é mais arrumadinho(a)?",
  "Quem canta no chuveiro?",
  "Quem se preocupa mais?",
  "Quem é melhor em puxar conversa?",
  "Quem faz um amigo novo numa festa?",
  "Quem resolve problemas melhor?",
  "Quem fica acordado(a) até tarde demais?",
  "Quem lembra melhor dos nomes?",
  "Quem cancela mais os planos?",
  "Quem é mais sincero(a)?",
  "Quem dá os melhores conselhos?",
  "Quem chora mais de alegria?",
  "Quem se atrasa mais?",
  "Quem cuida melhor das plantas?",
  "Quem é mais chato(a) para comer?",
  "Quem começa um projeto e não termina?",
  "Quem negocia melhor?",
  "Quem demora mais para escolher o que assistir?",
  "Quem conversa com o cachorro de um desconhecido?",
  "Quem se sai melhor numa emergência?",
  "Quem relê mais um livro favorito?",
  "Quem fala mais alto?",
  "Quem faz um desvio só pela vista?",
  "Quem mantém melhor uma rotina?",
  "Quem esquece onde estacionou?",
  "Quem é mais sentimental?",
  "Quem faz as melhores surpresas gastando pouco?",
  "Quem tenta consertar as coisas por conta própria?",
  "Quem pede desculpas sem ninguém pedir?",
  "Quem cairia num e-mail de golpe?",
  "Quem ensina melhor?",
  "Quem guarda mais rancor?",
  "Quem espera melhor?",
  "Quem muda o plano de última hora?",
  "Quem é mais curioso(a)?",
  "Quem percebe melhor o clima do ambiente?",
  "Quem não acorda com o despertador?",
  "Quem é mais generoso(a)?",
  "Quem mantém melhor a calma?",
  "Quem sempre quer sobremesa?",
  "Quem lembra melhor do que o outro disse?",
  "Quem começa a dançar primeiro?",
  "Quem se arrisca mais?",
  "Quem é melhor em não fazer nada?",
  "Quem prefere ligar a mandar mensagem?",
  "Quem é mais esperançoso(a)?",
  "Quem termina melhor uma discussão?",
  "Quem se prepara para o pior?",
  "Quem faz o outro rir melhor?",
  "Quem diz “eu te amo” primeiro?",
  "Quem é a melhor companhia de viagem?",
  "Quem vai lembrar de hoje daqui a um ano?",
];
