/* Strings for the guided tour and its demo partner.

   Kept out of i18n.js on purpose: that file is already two thousand lines of UI
   labels, and burying a tour that we expect to keep rewriting inside it is how
   the last one went three versions without anyone touching the copy.

   Deliberately terse. The first draft explained each step in two or three
   sentences and the tour read as a wall of text over a dimmed page — which is
   the opposite of the point, since the instruction is almost always just "tap
   the thing that's lit up". A title and at most one line. The spotlight says
   where; the body only says why, and only when that isn't obvious.

   `{n}` in a title or body is the demo partner's name. */

export const TUTORIAL_T = {
  en: {
    tutStart: "Show me",
    tutNext: "Next",
    tutExit: "Exit the tour",
    tutYourTurn: "Your turn",

    tutWelcomeTitle: "Let's write one together",
    tutWelcomeBody: "A few taps on the real pages. No explaining.",

    tutPromptTitle: "Today's little prompt",
    tutPromptBody: "Tap the box and answer it. One line is plenty.",
    tutHappyTitle: "Something good",
    tutHappyBody: "The smaller the better. Tap the card.",
    tutMindTitle: "Something on your mind",
    tutMindBody: "For the heavier things. If it might sting, Futari offers a gentler wording.",
    tutMoodTitle: "How today felt",
    tutMoodBody: "Tap whichever is closest.",
    tutSaveTitle: "Save the page",
    tutSaveBody: "That's a day, kept.",
    tutJournalTitle: "Every page you keep",
    tutJournalBody: "Days you've written on are marked. Tap one later to reopen it.",

    tutDemoIntroTitle: "Now the part for two",
    tutDemoIntroBody: "Try it with {n}, a stand-in, before inviting anyone. Nothing here is saved.",
    tutDemoCta: "Try it now",
    tutDemoPromptTitle: "{n} has already written",
    tutDemoPromptBody: "Sealed until you write too.",
    tutDemoHappyTitle: "One more line",
    tutDemoHappyBody: "Then you're both done.",
    tutDemoRevealTitle: "Open them together",
    tutDemoRevealBody: "This is the bit people stay for.",
    tutDemoPartnerTitle: "There they are",
    tutDemoPartnerBody: "Written without seeing yours. With a real partner it lands at the same moment.",
    tutDemoRespondTitle: "Say something back",
    tutDemoRespondBody: "A heart, or a line.",
    tutDemoDoneTitle: "That's Futari",
    tutDemoDoneBody: "Write apart, open together. Two things left.",

    tutNotifTitle: "One quiet nudge a day",
    tutNotifBody: "One in the evening, one when your partner finishes. Nothing else.",
    tutNotifCta: "Turn on reminders",
    tutNotifLater: "Not now",

    tutInviteTitle: "Now the real thing",
    tutInviteBody: "Send a link — one tap and you're paired. Your first five days are free.",
    tutInviteCta: "Invite my partner",
    tutInviteLater: "I'll do it later",

    demoPartnerName: "Mio",
    demoPartnerHappy: "You laughed at something on the train and didn't notice me watching.",
    demoPartnerMind: "I've been quieter this week — it's tiredness, not you. I didn't want you wondering.",
    demoPartnerNext: "Let's walk the long way home on Sunday, with no plan.",
    demoPartnerPromptAnswer: "The way the kitchen smelled when I got in.",
    demoPartnerReply: "Reading that made my whole evening ♡",
    demoSharedGoal: "Be kinder about Sundays.",
    demoNextPlan: "That little place by the river.",
  },

  es: {
    tutStart: "Enséñame",
    tutNext: "Siguiente",
    tutExit: "Salir del tour",
    tutYourTurn: "Te toca",

    tutWelcomeTitle: "Escribamos uno juntos",
    tutWelcomeBody: "Unos toques en las páginas de verdad. Sin explicaciones.",

    tutPromptTitle: "La pregunta de hoy",
    tutPromptBody: "Toca la caja y contéstala. Con una línea basta.",
    tutHappyTitle: "Algo bueno",
    tutHappyBody: "Cuanto más pequeño, mejor. Toca la tarjeta.",
    tutMindTitle: "Algo que te ronda",
    tutMindBody: "Para lo que pesa. Si puede doler, Futari propone una forma más suave.",
    tutMoodTitle: "Cómo se sintió hoy",
    tutMoodBody: "Toca el que más se acerque.",
    tutSaveTitle: "Guarda la página",
    tutSaveBody: "Un día, guardado.",
    tutJournalTitle: "Todas tus páginas",
    tutJournalBody: "Los días que escribiste quedan marcados. Luego podrás tocar uno para reabrirlo.",

    tutDemoIntroTitle: "Ahora la parte de dos",
    tutDemoIntroBody: "Pruébalo con {n}, alguien de mentira, antes de invitar a nadie. Nada se guarda.",
    tutDemoCta: "Probarlo ahora",
    tutDemoPromptTitle: "{n} ya ha escrito",
    tutDemoPromptBody: "Sellado hasta que escribas tú.",
    tutDemoHappyTitle: "Una línea más",
    tutDemoHappyBody: "Y ya estaréis los dos.",
    tutDemoRevealTitle: "Abridlas a la vez",
    tutDemoRevealBody: "Esto es por lo que la gente se queda.",
    tutDemoPartnerTitle: "Ahí está",
    tutDemoPartnerBody: "Escrita sin ver la tuya. Con alguien real llega en el mismo instante.",
    tutDemoRespondTitle: "Devuélvele algo",
    tutDemoRespondBody: "Un corazón, o una línea.",
    tutDemoDoneTitle: "Esto es Futari",
    tutDemoDoneBody: "Escribir aparte, abrir juntos. Quedan dos cosas.",

    tutNotifTitle: "Un aviso tranquilo al día",
    tutNotifBody: "Uno por la tarde, otro cuando tu pareja termine. Nada más.",
    tutNotifCta: "Activar recordatorios",
    tutNotifLater: "Ahora no",

    tutInviteTitle: "Ahora de verdad",
    tutInviteBody: "Manda un enlace: un toque y estáis vinculados. Los primeros cinco días son gratis.",
    tutInviteCta: "Invitar a mi pareja",
    tutInviteLater: "Lo hago luego",

    demoPartnerName: "Mio",
    demoPartnerHappy: "Te reíste de algo en el tren y no notaste que te estaba mirando.",
    demoPartnerMind: "He estado más callada esta semana — es cansancio, no tú. No quería que le dieras vueltas.",
    demoPartnerNext: "Volvamos a casa por el camino largo el domingo, sin plan.",
    demoPartnerPromptAnswer: "Cómo olía la cocina al entrar.",
    demoPartnerReply: "Leer eso me ha hecho la tarde entera ♡",
    demoSharedGoal: "Ser más amables con los domingos.",
    demoNextPlan: "Ese sitio pequeño junto al río.",
  },

  fr: {
    tutStart: "Montre-moi",
    tutNext: "Suivant",
    tutExit: "Quitter le guide",
    tutYourTurn: "À toi",

    tutWelcomeTitle: "Écrivons-en une ensemble",
    tutWelcomeBody: "Quelques gestes sur les vraies pages. Sans explications.",

    tutPromptTitle: "La question du jour",
    tutPromptBody: "Touche le cadre et réponds. Une ligne suffit.",
    tutHappyTitle: "Quelque chose de bien",
    tutHappyBody: "Plus c'est petit, mieux c'est. Touche la carte.",
    tutMindTitle: "Ce qui te trotte dans la tête",
    tutMindBody: "Pour ce qui pèse. Si ça risque de piquer, Futari propose plus doux.",
    tutMoodTitle: "L'humeur du jour",
    tutMoodBody: "Touche celle qui s'en rapproche.",
    tutSaveTitle: "Enregistre la page",
    tutSaveBody: "Une journée, gardée.",
    tutJournalTitle: "Toutes tes pages",
    tutJournalBody: "Les jours écrits sont marqués. Plus tard, touche-en un pour le rouvrir.",

    tutDemoIntroTitle: "Maintenant, à deux",
    tutDemoIntroBody: "Essaie avec {n}, une doublure, avant d'inviter qui que ce soit. Rien n'est enregistré.",
    tutDemoCta: "Essayer maintenant",
    tutDemoPromptTitle: "{n} a déjà écrit",
    tutDemoPromptBody: "Scellé tant que tu n'as pas écrit.",
    tutDemoHappyTitle: "Encore une ligne",
    tutDemoHappyBody: "Et vous aurez fini tous les deux.",
    tutDemoRevealTitle: "Ouvrez en même temps",
    tutDemoRevealBody: "C'est pour ce moment qu'on reste.",
    tutDemoPartnerTitle: "La voilà",
    tutDemoPartnerBody: "Écrite sans voir la tienne. Avec quelqu'un de réel, ça arrive au même instant.",
    tutDemoRespondTitle: "Réponds-lui",
    tutDemoRespondBody: "Un cœur, ou une ligne.",
    tutDemoDoneTitle: "Voilà Futari",
    tutDemoDoneBody: "Écrire séparément, ouvrir ensemble. Encore deux choses.",

    tutNotifTitle: "Un rappel discret par jour",
    tutNotifBody: "Un le soir, un quand ton partenaire a fini. Rien d'autre.",
    tutNotifCta: "Activer les rappels",
    tutNotifLater: "Pas maintenant",

    tutInviteTitle: "Passons au vrai",
    tutInviteBody: "Envoie un lien : une touche et vous êtes liés. Vos cinq premiers jours sont offerts.",
    tutInviteCta: "Inviter mon partenaire",
    tutInviteLater: "Plus tard",

    demoPartnerName: "Mio",
    demoPartnerHappy: "Tu as ri de quelque chose dans le train sans voir que je te regardais.",
    demoPartnerMind: "J'ai été plus silencieuse cette semaine — c'est la fatigue, pas toi. Je ne voulais pas que tu te poses la question.",
    demoPartnerNext: "Rentrons par le chemin le plus long dimanche, sans rien prévoir.",
    demoPartnerPromptAnswer: "L'odeur de la cuisine en rentrant.",
    demoPartnerReply: "Lire ça a illuminé toute ma soirée ♡",
    demoSharedGoal: "Être plus doux avec les dimanches.",
    demoNextPlan: "Ce petit endroit au bord de la rivière.",
  },

  de: {
    tutStart: "Zeig es mir",
    tutNext: "Weiter",
    tutExit: "Tour beenden",
    tutYourTurn: "Du bist dran",

    tutWelcomeTitle: "Schreiben wir eine zusammen",
    tutWelcomeBody: "Ein paar Schritte auf den echten Seiten. Ohne Erklärungen.",

    tutPromptTitle: "Die Frage von heute",
    tutPromptBody: "Tippe das Feld an und antworte. Eine Zeile reicht.",
    tutHappyTitle: "Etwas Gutes",
    tutHappyBody: "Je kleiner, desto besser. Tippe die Karte an.",
    tutMindTitle: "Was dir im Kopf herumgeht",
    tutMindBody: "Für das Schwerere. Klingt es scharf, schlägt Futari etwas Sanfteres vor.",
    tutMoodTitle: "Wie sich heute anfühlte",
    tutMoodBody: "Tippe, was am nächsten kommt.",
    tutSaveTitle: "Seite sichern",
    tutSaveBody: "Ein Tag, behalten.",
    tutJournalTitle: "Alle deine Seiten",
    tutJournalBody: "Tage mit Eintrag sind markiert. Später kannst du einen antippen, um ihn zu öffnen.",

    tutDemoIntroTitle: "Jetzt der Teil zu zweit",
    tutDemoIntroBody: "Probier es mit {n}, einer Platzhalterin, bevor du jemanden einlädst. Nichts wird gespeichert.",
    tutDemoCta: "Jetzt ausprobieren",
    tutDemoPromptTitle: "{n} hat schon geschrieben",
    tutDemoPromptBody: "Versiegelt, bis du auch schreibst.",
    tutDemoHappyTitle: "Noch eine Zeile",
    tutDemoHappyBody: "Dann seid ihr beide fertig.",
    tutDemoRevealTitle: "Gemeinsam öffnen",
    tutDemoRevealBody: "Dafür bleiben die Leute.",
    tutDemoPartnerTitle: "Da ist sie",
    tutDemoPartnerBody: "Geschrieben, ohne deine zu sehen. Mit einem echten Menschen kommt das im selben Moment.",
    tutDemoRespondTitle: "Antworte etwas",
    tutDemoRespondBody: "Ein Herz, oder eine Zeile.",
    tutDemoDoneTitle: "Das ist Futari",
    tutDemoDoneBody: "Getrennt schreiben, gemeinsam öffnen. Noch zwei Dinge.",

    tutNotifTitle: "Einmal am Tag, leise",
    tutNotifBody: "Eine am Abend, eine wenn dein Gegenüber fertig ist. Sonst nichts.",
    tutNotifCta: "Erinnerungen einschalten",
    tutNotifLater: "Jetzt nicht",

    tutInviteTitle: "Und jetzt echt",
    tutInviteBody: "Schick einen Link — ein Tipp und ihr seid verbunden. Die ersten fünf Tage sind frei.",
    tutInviteCta: "Partner einladen",
    tutInviteLater: "Später",

    demoPartnerName: "Mio",
    demoPartnerHappy: "Du hast im Zug über irgendetwas gelacht und nicht gemerkt, dass ich zusehe.",
    demoPartnerMind: "Ich war diese Woche stiller — das ist Müdigkeit, nicht du. Ich wollte nicht, dass du grübelst.",
    demoPartnerNext: "Lass uns am Sonntag den langen Weg nach Hause nehmen, ohne Plan.",
    demoPartnerPromptAnswer: "Wie die Küche gerochen hat, als ich reinkam.",
    demoPartnerReply: "Das zu lesen hat mir den ganzen Abend gerettet ♡",
    demoSharedGoal: "Freundlicher mit Sonntagen umgehen.",
    demoNextPlan: "Der kleine Laden am Fluss.",
  },

  it: {
    tutStart: "Fammi vedere",
    tutNext: "Avanti",
    tutExit: "Esci dal tour",
    tutYourTurn: "Tocca a te",

    tutWelcomeTitle: "Scriviamone una insieme",
    tutWelcomeBody: "Pochi tocchi sulle pagine vere. Senza spiegazioni.",

    tutPromptTitle: "La domanda di oggi",
    tutPromptBody: "Tocca il riquadro e rispondi. Basta una riga.",
    tutHappyTitle: "Qualcosa di bello",
    tutHappyBody: "Più è piccolo, meglio è. Tocca la scheda.",
    tutMindTitle: "Qualcosa che ti gira in testa",
    tutMindBody: "Per le cose pesanti. Se può pungere, Futari propone un modo più gentile.",
    tutMoodTitle: "Com'è andata oggi",
    tutMoodBody: "Tocca quella che ci si avvicina di più.",
    tutSaveTitle: "Salva la pagina",
    tutSaveBody: "Un giorno, tenuto.",
    tutJournalTitle: "Tutte le tue pagine",
    tutJournalBody: "I giorni scritti restano segnati. Più tardi potrai toccarne uno per riaprirlo.",

    tutDemoIntroTitle: "Ora la parte in due",
    tutDemoIntroBody: "Provalo con {n}, una controfigura, prima di invitare qualcuno. Non si salva nulla.",
    tutDemoCta: "Provalo ora",
    tutDemoPromptTitle: "{n} ha già scritto",
    tutDemoPromptBody: "Sigillata finché non scrivi anche tu.",
    tutDemoHappyTitle: "Ancora una riga",
    tutDemoHappyBody: "Poi avrete finito entrambi.",
    tutDemoRevealTitle: "Apritele insieme",
    tutDemoRevealBody: "È per questo che la gente resta.",
    tutDemoPartnerTitle: "Eccola",
    tutDemoPartnerBody: "Scritta senza vedere la tua. Con una persona vera arriva nello stesso istante.",
    tutDemoRespondTitle: "Rispondi qualcosa",
    tutDemoRespondBody: "Un cuore, o una riga.",
    tutDemoDoneTitle: "Questo è Futari",
    tutDemoDoneBody: "Scrivere separati, aprire insieme. Mancano due cose.",

    tutNotifTitle: "Un promemoria discreto al giorno",
    tutNotifBody: "Uno la sera, uno quando l'altra persona ha finito. Nient'altro.",
    tutNotifCta: "Attiva i promemoria",
    tutNotifLater: "Non ora",

    tutInviteTitle: "Ora quello vero",
    tutInviteBody: "Manda un link: un tocco e siete collegati. I primi cinque giorni sono gratis.",
    tutInviteCta: "Invita il mio partner",
    tutInviteLater: "Lo farò dopo",

    demoPartnerName: "Mio",
    demoPartnerHappy: "Hai riso per qualcosa sul treno senza accorgerti che ti guardavo.",
    demoPartnerMind: "Questa settimana sono stata più zitta — è stanchezza, non sei tu. Non volevo che ci pensassi su.",
    demoPartnerNext: "Domenica torniamo a casa dalla strada lunga, senza programmi.",
    demoPartnerPromptAnswer: "Il profumo della cucina quando sono entrata.",
    demoPartnerReply: "Leggerlo mi ha sistemato tutta la serata ♡",
    demoSharedGoal: "Essere più gentili con le domeniche.",
    demoNextPlan: "Quel postino vicino al fiume.",
  },

  ja: {
    tutStart: "やってみる",
    tutNext: "次へ",
    tutExit: "チュートリアルを終える",
    tutYourTurn: "どうぞ",

    tutWelcomeTitle: "いっしょに1ページ書こう",
    tutWelcomeBody: "説明はしません。実際の画面を数回タップするだけ。",

    tutPromptTitle: "今日のお題",
    tutPromptBody: "枠をタップして、一行だけでも答えてみて。",
    tutHappyTitle: "うれしかったこと",
    tutHappyBody: "小さいほどいい。カードをタップ。",
    tutMindTitle: "気になっていること",
    tutMindBody: "重たいこと用。きつく聞こえそうなら、やさしい言い方を提案するよ。",
    tutMoodTitle: "今日の気分",
    tutMoodBody: "近いものをタップするだけ。",
    tutSaveTitle: "ページを保存",
    tutSaveBody: "これで一日がひとつ残る。",
    tutJournalTitle: "書いたページは全部ここ",
    tutJournalBody: "書いた日には印がつくよ。あとでタップすれば開き直せる。",

    tutDemoIntroTitle: "ここからは、ふたり用",
    tutDemoIntroBody: "誰かを誘う前に、代役の{n}と試してみよう。この分は保存されないよ。",
    tutDemoCta: "試してみる",
    tutDemoPromptTitle: "{n}はもう書き終えてる",
    tutDemoPromptBody: "あなたが書くまで開けないよ。",
    tutDemoHappyTitle: "もう一行だけ",
    tutDemoHappyBody: "これでふたりとも書き終わり。",
    tutDemoRevealTitle: "せーので開こう",
    tutDemoRevealBody: "この瞬間のために続ける人が多いよ。",
    tutDemoPartnerTitle: "これが相手のページ",
    tutDemoPartnerBody: "あなたのを見ずに書いたもの。本物の相手とは同時に届くよ。",
    tutDemoRespondTitle: "何か返してみよう",
    tutDemoRespondBody: "ハートひとつでも、一行でも。",
    tutDemoDoneTitle: "これがFutari",
    tutDemoDoneBody: "別々に書いて、いっしょに開く。あと2つ。",

    tutNotifTitle: "1日1回だけ、そっと",
    tutNotifBody: "夜に1通と、相手が書き終わったとき1通。それだけ。",
    tutNotifCta: "リマインダーをオンにする",
    tutNotifLater: "いまはしない",

    tutInviteTitle: "じゃあ、本物の相手と",
    tutInviteBody: "リンクを送るだけ。タップでペア成立。最初の5日は無料。",
    tutInviteCta: "相手を招待する",
    tutInviteLater: "あとでやる",

    demoPartnerName: "ミオ",
    demoPartnerHappy: "電車で何かに笑ってたでしょ。見られてるの、気づいてなかったね。",
    demoPartnerMind: "今週ちょっと静かだったのは、疲れてるだけ。あなたのせいじゃないよ。気にさせたくなくて書いた。",
    demoPartnerNext: "日曜、遠回りして帰らない？予定は決めずに。",
    demoPartnerPromptAnswer: "帰ったときの、台所のにおい。",
    demoPartnerReply: "それ読んだだけで、今日の夜がぜんぶよくなった ♡",
    demoSharedGoal: "日曜をもう少しやさしく過ごす。",
    demoNextPlan: "川沿いの、あの小さい店。",
  },

  pt: {
    tutStart: "Me mostra",
    tutNext: "Próximo",
    tutExit: "Sair do tour",
    tutYourTurn: "Sua vez",

    tutWelcomeTitle: "Vamos escrever uma juntos",
    tutWelcomeBody: "Alguns toques nas páginas de verdade. Sem explicações.",

    tutPromptTitle: "A perguntinha de hoje",
    tutPromptBody: "Toque na caixa e responda. Uma linha já basta.",
    tutHappyTitle: "Algo bom",
    tutHappyBody: "Quanto menor, melhor. Toque no cartão.",
    tutMindTitle: "Algo na sua cabeça",
    tutMindBody: "Para o que pesa mais. Se puder machucar, o Futari sugere um jeito mais gentil.",
    tutMoodTitle: "Como foi o dia",
    tutMoodBody: "Toque no que chegar mais perto.",
    tutSaveTitle: "Salve a página",
    tutSaveBody: "Um dia, guardado.",
    tutJournalTitle: "Todas as suas páginas",
    tutJournalBody: "Os dias em que você escreveu ficam marcados. Depois é só tocar em um para reabrir.",

    tutDemoIntroTitle: "Agora a parte a dois",
    tutDemoIntroBody: "Experimente com {n}, uma substituta, antes de convidar alguém. Nada disso é salvo.",
    tutDemoCta: "Experimentar agora",
    tutDemoPromptTitle: "{n} já escreveu",
    tutDemoPromptBody: "Fechado até você escrever também.",
    tutDemoHappyTitle: "Só mais uma linha",
    tutDemoHappyBody: "E vocês dois terão terminado.",
    tutDemoRevealTitle: "Abram juntos",
    tutDemoRevealBody: "É por este momento que as pessoas ficam.",
    tutDemoPartnerTitle: "Aí está",
    tutDemoPartnerBody: "Escrita sem ver a sua. Com alguém de verdade, chega no mesmo instante.",
    tutDemoRespondTitle: "Responda algo",
    tutDemoRespondBody: "Um coração, ou uma linha.",
    tutDemoDoneTitle: "Isso é o Futari",
    tutDemoDoneBody: "Escrever separados, abrir juntos. Faltam duas coisas.",

    tutNotifTitle: "Um lembrete discreto por dia",
    tutNotifBody: "Um à noite, outro quando seu par terminar. Nada mais.",
    tutNotifCta: "Ativar lembretes",
    tutNotifLater: "Agora não",

    tutInviteTitle: "Agora para valer",
    tutInviteBody: "Envie um link — um toque e vocês formam par. Os primeiros cinco dias são grátis.",
    tutInviteCta: "Convidar meu par",
    tutInviteLater: "Faço depois",

    demoPartnerName: "Mio",
    demoPartnerHappy: "Você riu de alguma coisa no trem e nem percebeu que eu estava olhando.",
    demoPartnerMind: "Andei mais quieta esta semana — é cansaço, não é você. Não queria que você ficasse pensando.",
    demoPartnerNext: "Vamos voltar para casa pelo caminho mais longo no domingo, sem plano.",
    demoPartnerPromptAnswer: "O cheiro da cozinha quando cheguei.",
    demoPartnerReply: "Ler isso fez a minha noite inteira ♡",
    demoSharedGoal: "Ser mais gentis com os domingos.",
    demoNextPlan: "Aquele lugarzinho perto do rio.",
  },

  id: {
    tutStart: "Tunjukkan",
    tutNext: "Lanjut",
    tutExit: "Keluar dari tur",
    tutYourTurn: "Giliranmu",

    tutWelcomeTitle: "Yuk tulis satu bersama",
    tutWelcomeBody: "Beberapa ketukan di halaman aslinya. Tanpa penjelasan.",

    tutPromptTitle: "Pertanyaan kecil hari ini",
    tutPromptBody: "Ketuk kotaknya dan jawab. Satu baris sudah cukup.",
    tutHappyTitle: "Sesuatu yang baik",
    tutHappyBody: "Makin kecil makin bagus. Ketuk kartunya.",
    tutMindTitle: "Yang lagi kamu pikirkan",
    tutMindBody: "Untuk hal yang lebih berat. Kalau bisa menyakitkan, Futari menawarkan kata-kata yang lebih lembut.",
    tutMoodTitle: "Rasanya hari ini",
    tutMoodBody: "Ketuk yang paling mendekati.",
    tutSaveTitle: "Simpan halamannya",
    tutSaveBody: "Satu hari, tersimpan.",
    tutJournalTitle: "Semua halamanmu",
    tutJournalBody: "Hari yang sudah kamu tulis diberi tanda. Nanti tinggal ketuk untuk membukanya lagi.",

    tutDemoIntroTitle: "Sekarang bagian berdua",
    tutDemoIntroBody: "Coba dulu dengan {n}, pemeran pengganti, sebelum mengajak siapa pun. Ini tidak disimpan.",
    tutDemoCta: "Coba sekarang",
    tutDemoPromptTitle: "{n} sudah menulis",
    tutDemoPromptBody: "Tersegel sampai kamu juga menulis.",
    tutDemoHappyTitle: "Satu baris lagi",
    tutDemoHappyBody: "Lalu kalian berdua selesai.",
    tutDemoRevealTitle: "Buka bersama-sama",
    tutDemoRevealBody: "Momen inilah yang bikin orang bertahan.",
    tutDemoPartnerTitle: "Ini dia",
    tutDemoPartnerBody: "Ditulis tanpa melihat punyamu. Dengan pasangan sungguhan, sampainya di saat yang sama.",
    tutDemoRespondTitle: "Balas sesuatu",
    tutDemoRespondBody: "Satu hati, atau satu baris.",
    tutDemoDoneTitle: "Itulah Futari",
    tutDemoDoneBody: "Menulis terpisah, membuka bersama. Tinggal dua hal lagi.",

    tutNotifTitle: "Satu pengingat pelan sehari",
    tutNotifBody: "Satu di malam hari, satu saat pasanganmu selesai. Itu saja.",
    tutNotifCta: "Nyalakan pengingat",
    tutNotifLater: "Nanti saja",

    tutInviteTitle: "Sekarang yang sungguhan",
    tutInviteBody: "Kirim tautan — sekali ketuk dan kalian berpasangan. Lima hari pertama gratis.",
    tutInviteCta: "Undang pasanganku",
    tutInviteLater: "Nanti kulakukan",

    demoPartnerName: "Mio",
    demoPartnerHappy: "Kamu ketawa karena sesuatu di kereta dan nggak sadar aku memperhatikan.",
    demoPartnerMind: "Minggu ini aku lebih pendiam — itu karena capek, bukan karena kamu. Aku nggak mau kamu bertanya-tanya.",
    demoPartnerNext: "Hari Minggu kita pulang lewat jalan yang jauh yuk, tanpa rencana.",
    demoPartnerPromptAnswer: "Aroma dapur waktu aku sampai di rumah.",
    demoPartnerReply: "Baca itu bikin malamku jadi indah ♡",
    demoSharedGoal: "Lebih santai di hari Minggu.",
    demoNextPlan: "Tempat kecil di tepi sungai itu.",
  },

  zh: {
    tutStart: "试试看",
    tutNext: "下一步",
    tutExit: "退出引导",
    tutYourTurn: "该你了",

    tutWelcomeTitle: "一起写一页吧",
    tutWelcomeBody: "不讲解，只在真实的页面上点几下。",

    tutPromptTitle: "今日小话题",
    tutPromptBody: "点一下输入框，写一行就够了。",
    tutHappyTitle: "开心的事",
    tutHappyBody: "越小越好。点一下卡片。",
    tutMindTitle: "在意的事",
    tutMindBody: "用来写比较沉的事。如果可能伤人，Futari 会建议更温柔的说法。",
    tutMoodTitle: "今天的心情",
    tutMoodBody: "点最接近的那个就好。",
    tutSaveTitle: "保存这一页",
    tutSaveBody: "这一天，就这样留下了。",
    tutJournalTitle: "写过的页面都在这里",
    tutJournalBody: "写过的日子会有标记。之后点一下就能重新打开。",

    tutDemoIntroTitle: "接下来是两个人的部分",
    tutDemoIntroBody: "在邀请别人之前，先和替身 {n} 试一试。这部分不会保存。",
    tutDemoCta: "现在试试",
    tutDemoPromptTitle: "{n} 已经写好了",
    tutDemoPromptBody: "在你写之前，它是封着的。",
    tutDemoHappyTitle: "再写一行",
    tutDemoHappyBody: "这样你们俩就都写完了。",
    tutDemoRevealTitle: "一起打开",
    tutDemoRevealBody: "很多人就是为了这一刻留下来的。",
    tutDemoPartnerTitle: "这就是对方的一页",
    tutDemoPartnerBody: "是在没看到你的内容时写的。和真正的对方一起时，会在同一刻送达。",
    tutDemoRespondTitle: "回点什么吧",
    tutDemoRespondBody: "一颗心，或者一句话。",
    tutDemoDoneTitle: "这就是 Futari",
    tutDemoDoneBody: "各自写，一起打开。还剩两件事。",

    tutNotifTitle: "每天一次，轻轻提醒",
    tutNotifBody: "晚上一条，对方写完时一条。仅此而已。",
    tutNotifCta: "开启提醒",
    tutNotifLater: "暂时不用",

    tutInviteTitle: "现在，来真的",
    tutInviteBody: "发一个链接，点一下就能配对。前五天免费。",
    tutInviteCta: "邀请另一半",
    tutInviteLater: "以后再说",

    demoPartnerName: "Mio",
    demoPartnerHappy: "你在电车上不知为什么笑了，没发现我一直在看你。",
    demoPartnerMind: "这周我比较安静，只是累了，不是因为你。不想让你多想，所以写下来。",
    demoPartnerNext: "周日我们绕远路回家吧，不做任何计划。",
    demoPartnerPromptAnswer: "回到家时，厨房里的味道。",
    demoPartnerReply: "读到这句，我整个晚上都变好了 ♡",
    demoSharedGoal: "把周日过得更温柔一点。",
    demoNextPlan: "河边的那家小店。",
  },

  ko: {
    tutStart: "해 볼게요",
    tutNext: "다음",
    tutExit: "튜토리얼 끝내기",
    tutYourTurn: "해 보세요",

    tutWelcomeTitle: "같이 한 페이지 써 봐요",
    tutWelcomeBody: "설명은 없어요. 실제 화면을 몇 번 누르기만 하면 돼요.",

    tutPromptTitle: "오늘의 작은 질문",
    tutPromptBody: "칸을 눌러서 한 줄만이라도 답해 보세요.",
    tutHappyTitle: "기뻤던 일",
    tutHappyBody: "작을수록 좋아요. 카드를 눌러 보세요.",
    tutMindTitle: "마음에 걸리는 일",
    tutMindBody: "무거운 이야기를 위한 곳이에요. 날카롭게 들릴 것 같으면 부드러운 표현을 제안해 드려요.",
    tutMoodTitle: "오늘의 기분",
    tutMoodBody: "가장 가까운 걸 누르기만 하면 돼요.",
    tutSaveTitle: "페이지 저장",
    tutSaveBody: "이렇게 하루가 하나 남아요.",
    tutJournalTitle: "쓴 페이지는 전부 여기에",
    tutJournalBody: "쓴 날에는 표시가 생겨요. 나중에 누르면 다시 열 수 있어요.",

    tutDemoIntroTitle: "이제부터는 둘이서",
    tutDemoIntroBody: "누군가를 초대하기 전에, 대역인 {n}와 먼저 해 봐요. 이 부분은 저장되지 않아요.",
    tutDemoCta: "해 보기",
    tutDemoPromptTitle: "{n}는 이미 다 썼어요",
    tutDemoPromptBody: "당신이 쓰기 전까지는 열 수 없어요.",
    tutDemoHappyTitle: "한 줄만 더",
    tutDemoHappyBody: "그러면 둘 다 다 쓴 거예요.",
    tutDemoRevealTitle: "하나, 둘, 셋 하고 열어요",
    tutDemoRevealBody: "이 순간 때문에 계속 쓰는 사람이 많아요.",
    tutDemoPartnerTitle: "이게 상대의 페이지",
    tutDemoPartnerBody: "당신 글을 보지 않고 쓴 거예요. 실제 상대와는 같은 순간에 도착해요.",
    tutDemoRespondTitle: "뭔가 답해 봐요",
    tutDemoRespondBody: "하트 하나도, 한 줄도 좋아요.",
    tutDemoDoneTitle: "이게 Futari예요",
    tutDemoDoneBody: "따로 쓰고, 같이 열어요. 이제 두 가지 남았어요.",

    tutNotifTitle: "하루에 한 번만, 살짝",
    tutNotifBody: "밤에 한 번, 상대가 다 썼을 때 한 번. 그게 전부예요.",
    tutNotifCta: "알림 켜기",
    tutNotifLater: "지금은 안 할래요",

    tutInviteTitle: "이제 진짜 상대와",
    tutInviteBody: "링크만 보내면 돼요. 누르면 바로 페어가 돼요. 처음 5일은 무료예요.",
    tutInviteCta: "상대 초대하기",
    tutInviteLater: "나중에 할게요",

    demoPartnerName: "미오",
    demoPartnerHappy: "지하철에서 뭔가 보고 웃었지? 내가 보고 있는 줄도 몰랐잖아.",
    demoPartnerMind: "이번 주에 좀 조용했던 건 피곤해서 그래. 너 때문이 아니야. 신경 쓸까 봐 적어 둬.",
    demoPartnerNext: "일요일에 멀리 돌아서 집에 갈래? 계획 없이.",
    demoPartnerPromptAnswer: "집에 들어섰을 때 나던 부엌 냄새.",
    demoPartnerReply: "그거 읽고 오늘 저녁이 통째로 좋아졌어 ♡",
    demoSharedGoal: "일요일을 조금 더 다정하게 보내기.",
    demoNextPlan: "강가에 있는 그 작은 가게.",
  },
};

/* The message that goes out with a pairing link.

   Separate from `inviteFriendMessage`, which is the generic "you might like this
   app" share: this one carries a code and is addressed to one specific person,
   so it says what tapping it will do. `{url}` is the pairing link. */
export const INVITE_T = {
  en: {
    pairInviteMessage:
      "I've started a little shared diary on Futari and I'd like to keep it with you ♡ Tap this and we're paired — no code to type: {url}",
    pairInviteShareTitle: "Write with me on Futari",
  },
  es: {
    pairInviteMessage:
      "He empezado un diario compartido en Futari y me gustaría llevarlo contigo ♡ Toca esto y quedamos vinculados, sin códigos: {url}",
    pairInviteShareTitle: "Escribe conmigo en Futari",
  },
  fr: {
    pairInviteMessage:
      "J'ai commencé un petit journal partagé sur Futari et j'aimerais le tenir avec toi ♡ Touche ce lien et on est liés, sans code : {url}",
    pairInviteShareTitle: "Écris avec moi sur Futari",
  },
  de: {
    pairInviteMessage:
      "Ich habe auf Futari ein kleines gemeinsames Tagebuch angefangen und würde es gern mit dir führen ♡ Tippe hier, dann sind wir verbunden — ohne Code: {url}",
    pairInviteShareTitle: "Schreib mit mir auf Futari",
  },
  it: {
    pairInviteMessage:
      "Ho iniziato un piccolo diario condiviso su Futari e mi piacerebbe tenerlo con te ♡ Tocca qui e siamo collegati, senza codici: {url}",
    pairInviteShareTitle: "Scrivi con me su Futari",
  },
  ja: {
    pairInviteMessage:
      "Futariっていう、ふたりで書く日記を始めたよ。よかったら一緒にどう？このリンクを開くだけでペアになるよ（コード入力はいらない）: {url}",
    pairInviteShareTitle: "Futariでいっしょに書こう",
  },
  pt: {
    pairInviteMessage:
      "Comecei um diário compartilhado no Futari e queria escrever ele com você ♡ Toque aqui e a gente forma par — sem código para digitar: {url}",
    pairInviteShareTitle: "Escreva comigo no Futari",
  },
  id: {
    pairInviteMessage:
      "Aku mulai buku harian berdua di Futari dan ingin menulisnya bareng kamu ♡ Ketuk ini dan kita langsung berpasangan — tanpa perlu mengetik kode: {url}",
    pairInviteShareTitle: "Menulis bareng aku di Futari",
  },
  zh: {
    pairInviteMessage:
      "我在 Futari 上开始写两个人的日记了，想和你一起写 ♡ 点开这个链接我们就能配对，不用输入邀请码：{url}",
    pairInviteShareTitle: "和我一起在 Futari 写日记",
  },
  ko: {
    pairInviteMessage:
      "Futari라는 둘이 쓰는 일기를 시작했어. 같이 쓰지 않을래? ♡ 이 링크만 열면 바로 페어가 돼 (코드 입력은 필요 없어): {url}",
    pairInviteShareTitle: "Futari에서 같이 써요",
  },
};
